-- Добавление демо-данных для WB товаров в public.cars
-- Type: 'wb_item', specs: {size, color, pattern, season, warehouse_locations: [{voxel_id, quantity}] JSONB array}

INSERT INTO public.cars (id, make, model, description, type, specs, image_url)
VALUES
-- Евро (бежевый, 180x220, лето/зима, все узоры)
('evro-leto-kruzheva', 'Евро', 'Лето Кружева', 'Бежевая, полосочка', 'wb_item', 
 '{"size": "180x220", "color": "beige", "pattern": "kruzheva", "season": "leto", "warehouse_locations": [{"voxel_id": "A1", "quantity": 5}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/evro-leto-kruzheva.jpg'),
('evro-zima-kruzheva', 'Евро', 'Зима Кружева', 'Бежевая, полузакрытая', 'wb_item', 
 '{"size": "180x220", "color": "beige", "pattern": "kruzheva", "season": "zima", "warehouse_locations": [{"voxel_id": "A1", "quantity": 3}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/evro-zima-kruzheva.jpg'),
('evro-leto-mirodel', 'Евро', 'Лето Миродель', 'Бежевая, фиолетовый узор', 'wb_item', 
 '{"size": "180x220", "color": "beige", "pattern": "mirodel", "season": "leto", "warehouse_locations": [{"voxel_id": "A1", "quantity": 7}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/evro-leto-mirodel.jpg'),
('evro-zima-mirodel', 'Евро', 'Зима Миродель', 'Бежевая, фиолетовый узор', 'wb_item', 
 '{"size": "180x220", "color": "beige", "pattern": "mirodel", "season": "zima", "warehouse_locations": [{"voxel_id": "A1", "quantity": 2}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/evro-zima-mirodel.jpg'),
('evro-leto-ogurtsy', 'Евро', 'Лето Огурцы', 'Бежевая, фрактальный узор', 'wb_item', 
 '{"size": "180x220", "color": "beige", "pattern": "ogurtsy", "season": "leto", "warehouse_locations": [{"voxel_id": "A1", "quantity": 4}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/evro-leto-ogurtsy.jpg'),
('evro-zima-ogurtsy', 'Евро', 'Зима Огурцы', 'Бежевая, фрактальный узор', 'wb_item', 
 '{"size": "180x220", "color": "beige", "pattern": "ogurtsy", "season": "zima", "warehouse_locations": [{"voxel_id": "A1", "quantity": 6}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/evro-zima-ogurtsy.jpg'),
('evro-leto-flora1', 'Евро', 'Лето Флора 1', 'Бежевая, маленькие цветочки', 'wb_item', 
 '{"size": "180x220", "color": "beige", "pattern": "flora1", "season": "leto", "warehouse_locations": [{"voxel_id": "A1", "quantity": 8}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/evro-leto-flora1.jpg'),
('evro-zima-flora1', 'Евро', 'Зима Флора 1', 'Бежевая, маленькие цветочки', 'wb_item', 
 '{"size": "180x220", "color": "beige", "pattern": "flora1", "season": "zima", "warehouse_locations": [{"voxel_id": "A1", "quantity": 1}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/evro-zima-flora1.jpg'),
('evro-leto-flora2', 'Евро', 'Лето Флора 2', 'Бежевая, средние цветочки', 'wb_item', 
 '{"size": "180x220", "color": "beige", "pattern": "flora2", "season": "leto", "warehouse_locations": [{"voxel_id": "A1", "quantity": 9}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/evro-leto-flora2.jpg'),
('evro-zima-flora2', 'Евро', 'Зима Флора 2', 'Бежевая, средние цветочки', 'wb_item', 
 '{"size": "180x220", "color": "beige", "pattern": "flora2", "season": "zima", "warehouse_locations": [{"voxel_id": "A1", "quantity": 10}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/evro-zima-flora2.jpg'),
('evro-leto-flora3', 'Евро', 'Лето Флора 3', 'Бежевая, большие цветочки', 'wb_item', 
 '{"size": "180x220", "color": "beige", "pattern": "flora3", "season": "leto", "warehouse_locations": [{"voxel_id": "A1", "quantity": 3}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/evro-leto-flora3.jpg'),
('evro-zima-flora3', 'Евро', 'Зима Флора 3', 'Бежевая, большие цветочки', 'wb_item', 
 '{"size": "180x220", "color": "beige", "pattern": "flora3", "season": "zima", "warehouse_locations": [{"voxel_id": "A1", "quantity": 5}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/evro-zima-flora3.jpg'),

-- Двушки (голубой, 200x220, лето/зима, все узоры)
('dvushka-leto-kruzheva', 'Двушка', 'Лето Кружева', 'Голубая, полосочка', 'wb_item', 
 '{"size": "200x220", "color": "blue", "pattern": "kruzheva", "season": "leto", "warehouse_locations": [{"voxel_id": "A2", "quantity": 4}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/dvushka-leto-kruzheva.jpg'),
('dvushka-zima-kruzheva', 'Двушка', 'Зима Кружева', 'Голубая, полузакрытая', 'wb_item', 
 '{"size": "200x220", "color": "blue", "pattern": "kruzheva", "season": "zima", "warehouse_locations": [{"voxel_id": "A2", "quantity": 6}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/dvushka-zima-kruzheva.jpg'),
('dvushka-leto-mirodel', 'Двушка', 'Лето Миродель', 'Голубая, фиолетовый узор', 'wb_item', 
 '{"size": "200x220", "color": "blue", "pattern": "mirodel", "season": "leto", "warehouse_locations": [{"voxel_id": "A2", "quantity": 2}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/dvushka-leto-mirodel.jpg'),
('dvushka-zima-mirodel', 'Двушка', 'Зима Миродель', 'Голубая, фиолетовый узор', 'wb_item', 
 '{"size": "200x220", "color": "blue", "pattern": "mirodel", "season": "zima", "warehouse_locations": [{"voxel_id": "A2", "quantity": 8}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/dvushka-zima-mirodel.jpg'),
('dvushka-leto-ogurtsy', 'Двушка', 'Лето Огурцы', 'Голубая, фрактальный узор', 'wb_item', 
 '{"size": "200x220", "color": "blue", "pattern": "ogurtsy", "season": "leto", "warehouse_locations": [{"voxel_id": "A2", "quantity": 1}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/dvushka-leto-ogurtsy.jpg'),
('dvushka-zima-ogurtsy', 'Двушка', 'Зима Огурцы', 'Голубая, фрактальный узор', 'wb_item', 
 '{"size": "200x220", "color": "blue", "pattern": "ogurtsy", "season": "zima", "warehouse_locations": [{"voxel_id": "A2", "quantity": 9}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/dvushka-zima-ogurtsy.jpg'),
('dvushka-leto-flora1', 'Двушка', 'Лето Флора 1', 'Голубая, маленькие цветочки', 'wb_item', 
 '{"size": "200x220", "color": "blue", "pattern": "flora1", "season": "leto", "warehouse_locations": [{"voxel_id": "A2", "quantity": 5}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/dvushka-leto-flora1.jpg'),
('dvushka-zima-flora1', 'Двушка', 'Зима Флора 1', 'Голубая, маленькие цветочки', 'wb_item', 
 '{"size": "200x220", "color": "blue", "pattern": "flora1", "season": "zima", "warehouse_locations": [{"voxel_id": "A2", "quantity": 7}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/dvushka-zima-flora1.jpg'),
('dvushka-leto-flora2', 'Двушка', 'Лето Флора 2', 'Голубая, средние цветочки', 'wb_item', 
 '{"size": "200x220", "color": "blue", "pattern": "flora2", "season": "leto", "warehouse_locations": [{"voxel_id": "A2", "quantity": 3}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/dvushka-leto-flora2.jpg'),
('dvushka-zima-flora2', 'Двушка', 'Зима Флора 2', 'Голубая, средние цветочки', 'wb_item', 
 '{"size": "200x220", "color": "blue", "pattern": "flora2", "season": "zima", "warehouse_locations": [{"voxel_id": "A2", "quantity": 10}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/dvushka-zima-flora2.jpg'),
('dvushka-leto-flora3', 'Двушка', 'Лето Флора 3', 'Голубая, большие цветочки', 'wb_item', 
 '{"size": "200x220", "color": "blue", "pattern": "flora3", "season": "leto", "warehouse_locations": [{"voxel_id": "A2", "quantity": 4}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/dvushka-leto-flora3.jpg'),
('dvushka-zima-flora3', 'Двушка', 'Зима Флора 3', 'Голубая, большие цветочки', 'wb_item', 
 '{"size": "200x220", "color": "blue", "pattern": "flora3", "season": "zima", "warehouse_locations": [{"voxel_id": "A2", "quantity": 6}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/dvushka-zima-flora3.jpg'),

-- Евро Макси (красный, 220x240, лето/зима, все узоры)
('evro-maksi-leto-kruzheva', 'Евро Макси', 'Лето Кружева', 'Красная, полосочка', 'wb_item', 
 '{"size": "220x240", "color": "red", "pattern": "kruzheva", "season": "leto", "warehouse_locations": [{"voxel_id": "A3", "quantity": 2}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/evro-maksi-leto-kruzheva.jpg'),
('evro-maksi-zima-kruzheva', 'Евро Макси', 'Зима Кружева', 'Красная, полузакрытая', 'wb_item', 
 '{"size": "220x240", "color": "red", "pattern": "kruzheva", "season": "zima", "warehouse_locations": [{"voxel_id": "A3", "quantity": 8}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/evro-maksi-zima-kruzheva.jpg'),
('evro-maksi-leto-mirodel', 'Евро Макси', 'Лето Миродель', 'Красная, фиолетовый узор', 'wb_item', 
 '{"size": "220x240", "color": "red", "pattern": "mirodel", "season": "leto", "warehouse_locations": [{"voxel_id": "A3", "quantity": 1}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/evro-maksi-leto-mirodel.jpg'),
('evro-maksi-zima-mirodel', 'Евро Макси', 'Зима Миродель', 'Красная, фиолетовый узор', 'wb_item', 
 '{"size": "220x240", "color": "red", "pattern": "mirodel", "season": "zima", "warehouse_locations": [{"voxel_id": "A3", "quantity": 9}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/evro-maksi-zima-mirodel.jpg'),
('evro-maksi-leto-ogurtsy', 'Евро Макси', 'Лето Огурцы', 'Красная, фрактальный узор', 'wb_item', 
 '{"size": "220x240", "color": "red", "pattern": "ogurtsy", "season": "leto", "warehouse_locations": [{"voxel_id": "A3", "quantity": 5}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/evro-maksi-leto-ogurtsy.jpg'),
('evro-maksi-zima-ogurtsy', 'Евро Макси', 'Зима Огурцы', 'Красная, фрактальный узор', 'wb_item', 
 '{"size": "220x240", "color": "red", "pattern": "ogurtsy", "season": "zima", "warehouse_locations": [{"voxel_id": "A3", "quantity": 7}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/evro-maksi-zima-ogurtsy.jpg'),
('evro-maksi-leto-flora1', 'Евро Макси', 'Лето Флора 1', 'Красная, маленькие цветочки', 'wb_item', 
 '{"size": "220x240", "color": "red", "pattern": "flora1", "season": "leto", "warehouse_locations": [{"voxel_id": "A3", "quantity": 3}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/evro-maksi-leto-flora1.jpg'),
('evro-maksi-zima-flora1', 'Евро Макси', 'Зима Флора 1', 'Красная, маленькие цветочки', 'wb_item', 
 '{"size": "220x240", "color": "red", "pattern": "flora1", "season": "zima", "warehouse_locations": [{"voxel_id": "A3", "quantity": 10}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/evro-maksi-zima-flora1.jpg'),
('evro-maksi-leto-flora2', 'Евро Макси', 'Лето Флора 2', 'Красная, средние цветочки', 'wb_item', 
 '{"size": "220x240", "color": "red", "pattern": "flora2", "season": "leto", "warehouse_locations": [{"voxel_id": "A3", "quantity": 4}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/evro-maksi-leto-flora2.jpg'),
('evro-maksi-zima-flora2', 'Евро Макси', 'Зима Флора 2', 'Красная, средние цветочки', 'wb_item', 
 '{"size": "220x240", "color": "red", "pattern": "flora2", "season": "zima", "warehouse_locations": [{"voxel_id": "A3", "quantity": 6}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/evro-maksi-zima-flora2.jpg'),
('evro-maksi-leto-flora3', 'Евро Макси', 'Лето Флора 3', 'Красная, большие цветочки', 'wb_item', 
 '{"size": "220x240", "color": "red", "pattern": "flora3", "season": "leto", "warehouse_locations": [{"voxel_id": "A3", "quantity": 2}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/evro-maksi-leto-flora3.jpg'),
('evro-maksi-zima-flora3', 'Евро Макси', 'Зима Флора 3', 'Красная, большие цветочки', 'wb_item', 
 '{"size": "220x240", "color": "red", "pattern": "flora3", "season": "zima", "warehouse_locations": [{"voxel_id": "A3", "quantity": 8}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/evro-maksi-zima-flora3.jpg'),

-- Матрасники (салатовый для 90/120/140, темно-зеленый для 160/180/200, только кружева, без сезона)
('matrasnik-90-kruzheva', 'Матрасник', '90 Кружева', 'Салатовый, маленький', 'wb_item', 
 '{"size": "90", "color": "light-green", "pattern": "kruzheva", "season": null, "warehouse_locations": [{"voxel_id": "A4", "quantity": 5}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/matrasnik-90-kruzheva.jpg'),
('matrasnik-120-kruzheva', 'Матрасник', '120 Кружева', 'Салатовый, маленький', 'wb_item', 
 '{"size": "120", "color": "light-green", "pattern": "kruzheva", "season": null, "warehouse_locations": [{"voxel_id": "A4", "quantity": 3}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/matrasnik-120-kruzheva.jpg'),
('matrasnik-140-kruzheva', 'Матрасник', '140 Кружева', 'Салатовый, маленький', 'wb_item', 
 '{"size": "140", "color": "light-green", "pattern": "kruzheva", "season": null, "warehouse_locations": [{"voxel_id": "A4", "quantity": 7}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/matrasnik-140-kruzheva.jpg'),
('matrasnik-160-kruzheva', 'Матрасник', '160 Кружева', 'Темно-зеленый, большой', 'wb_item', 
 '{"size": "160", "color": "dark-green", "pattern": "kruzheva", "season": null, "warehouse_locations": [{"voxel_id": "A4", "quantity": 2}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/matrasnik-160-kruzheva.jpg'),
('matrasnik-180-kruzheva', 'Матрасник', '180 Кружева', 'Темно-зеленый, большой', 'wb_item', 
 '{"size": "180", "color": "dark-green", "pattern": "kruzheva", "season": null, "warehouse_locations": [{"voxel_id": "A4", "quantity": 4}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/matrasnik-180-kruzheva.jpg'),
('matrasnik-200-kruzheva', 'Матрасник', '200 Кружева', 'Темно-зеленый, большой', 'wb_item', 
 '{"size": "200", "color": "dark-green", "pattern": "kruzheva", "season": null, "warehouse_locations": [{"voxel_id": "A4", "quantity": 6}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/matrasnik-200-kruzheva.jpg'),

-- Полуторки (серый, 150x200, лето/зима, все узоры)
('polutorka-leto-kruzheva', 'Полуторка', 'Лето Кружева', 'Серая, полосочка', 'wb_item', 
 '{"size": "150x200", "color": "gray", "pattern": "kruzheva", "season": "leto", "warehouse_locations": [{"voxel_id": "B1", "quantity": 8}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/polutorka-leto-kruzheva.jpg'),
('polutorka-zima-kruzheva', 'Полуторка', 'Зима Кружева', 'Серая, полузакрытая', 'wb_item', 
 '{"size": "150x200", "color": "gray", "pattern": "kruzheva", "season": "zima", "warehouse_locations": [{"voxel_id": "B1", "quantity": 1}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/polutorka-zima-kruzheva.jpg'),
('polutorka-leto-mirodel', 'Полуторка', 'Лето Миродель', 'Серая, фиолетовый узор', 'wb_item', 
 '{"size": "150x200", "color": "gray", "pattern": "mirodel", "season": "leto", "warehouse_locations": [{"voxel_id": "B1", "quantity": 9}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/polutorka-leto-mirodel.jpg'),
('polutorka-zima-mirodel', 'Полуторка', 'Зима Миродель', 'Серая, фиолетовый узор', 'wb_item', 
 '{"size": "150x200", "color": "gray", "pattern": "mirodel", "season": "zima", "warehouse_locations": [{"voxel_id": "B1", "quantity": 10}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/polutorka-zima-mirodel.jpg'),
('polutorka-leto-ogurtsy', 'Полуторка', 'Лето Огурцы', 'Серая, фрактальный узор', 'wb_item', 
 '{"size": "150x200", "color": "gray", "pattern": "ogurtsy", "season": "leto", "warehouse_locations": [{"voxel_id": "B1", "quantity": 3}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/polutorka-leto-ogurtsy.jpg'),
('polutorka-zima-ogurtsy', 'Полуторка', 'Зима Огурцы', 'Серая, фрактальный узор', 'wb_item', 
 '{"size": "150x200", "color": "gray", "pattern": "ogurtsy", "season": "zima", "warehouse_locations": [{"voxel_id": "B1", "quantity": 5}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/polutorka-zima-ogurtsy.jpg'),
('polutorka-leto-flora1', 'Полуторка', 'Лето Флора 1', 'Серая, маленькие цветочки', 'wb_item', 
 '{"size": "150x200", "color": "gray", "pattern": "flora1", "season": "leto", "warehouse_locations": [{"voxel_id": "B1", "quantity": 4}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/polutorka-leto-flora1.jpg'),
('polutorka-zima-flora1', 'Полуторка', 'Зима Флора 1', 'Серая, маленькие цветочки', 'wb_item', 
 '{"size": "150x200", "color": "gray", "pattern": "flora1", "season": "zima", "warehouse_locations": [{"voxel_id": "B1", "quantity": 6}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/polutorka-zima-flora1.jpg'),
('polutorka-leto-flora2', 'Полуторка', 'Лето Флора 2', 'Серая, средние цветочки', 'wb_item', 
 '{"size": "150x200", "color": "gray", "pattern": "flora2", "season": "leto", "warehouse_locations": [{"voxel_id": "B1", "quantity": 2}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/polutorka-leto-flora2.jpg'),
('polutorka-zima-flora2', 'Полуторка', 'Зима Флора 2', 'Серая, средние цветочки', 'wb_item', 
 '{"size": "150x200", "color": "gray", "pattern": "flora2", "season": "zima", "warehouse_locations": [{"voxel_id": "B1", "quantity": 8}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/polutorka-zima-flora2.jpg'),
('polutorka-leto-flora3', 'Полуторка', 'Лето Флора 3', 'Серая, большие цветочки', 'wb_item', 
 '{"size": "150x200", "color": "gray", "pattern": "flora3", "season": "leto", "warehouse_locations": [{"voxel_id": "B1", "quantity": 1}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/polutorka-leto-flora3.jpg'),
('polutorka-zima-flora3', 'Полуторка', 'Зима Флора 3', 'Серая, большие цветочки', 'wb_item', 
 '{"size": "150x200", "color": "gray", "pattern": "flora3", "season": "zima", "warehouse_locations": [{"voxel_id": "B1", "quantity": 7}]}',
 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/wb/polutorka-zima-flora3.jpg')

ON CONFLICT (id) DO UPDATE SET specs = EXCLUDED.specs;