import type * as Fa6Icons from "react-icons/fa6";

export const iconNameMap: { [key: string]: keyof typeof Fa6Icons } = {
  // General & UI
  fathumbsup: "FaThumbsUp",
  faeye: "FaEye",
  fakeyboard: "FaKeyboard",
  fawandmagicsparkles: "FaWandMagicSparkles",
  facheckdouble: "FaCheckDouble",
  fatools: "FaToolbox", // Corrected from FaTools
  falandmineon: "FaLandMineOn",
  fascrewdriverwrench: "FaScrewdriverWrench",
  fasmilewink: "FaSmileWink",
  fatriangleexclamation: "FaTriangleExclamation",
  facrosshairs: "FaCrosshairs",
  fabookmedical: "FaBookMedical",
  fashieldhalved: "FaShieldHalved",
  faaward: "FaAward",
  fabookopen: "FaBookOpen",
  fabrain: "FaBrain",
  fainfinity: "FaInfinity",
  farecycle: "FaRecycle",
  fashapes: "FaShapes",
  fahammer: "FaHammer",
  faprojectdiagram: "FaProjectDiagram",
  fabroadcasttower: "FaBroadcastTower",
  fauniversalaccess: "FaUniversalAccess",
  fabong: "FaBong",
  fafire: "FaFire",
  fasatellitedish: "FaSatelliteDish",
  falaptopcode: "FaLaptopCode",
  fatoolbox: "FaToolbox",
  falink: "FaLink",
  faupload: "FaUpload",
  facheck: "FaCheck",
  faexchangealt: "FaExchangeAlt", 
  faimageslash: "FaImageSlash",
  faimageportrait: "FaImagePortrait",
  faplaycircle: "FaPlayCircle",
  faexternallinkalt: "FaExternalLinkAlt", 
  fabomb: "FaBomb",
  famedal: "FaMedal",
  favideo: "FaVideo",
  favideoslash: "FaVideoSlash",
  fafilm: "FaFilm",
  faroad: "FaRoad",
  fauserninja: "FaUserNinja",
  fagamepad: "FaGamepad",
  facircleuser: "FaCircleUser",
  facreditcard: "FaCreditCard",
  fastar: "FaStar",
  fagears: "FaGears",
  fausers: "FaUsers",
  farocket: "FaRocket",
  fanetworkwired: "FaNetworkWired",
  fareglightbulb: "FaRegLightbulb",
  fapalette: "FaPalette",
  facircleinfo: "FaCircleInfo",
  fadollarsign: "FaDollarSign",
  facaron: "FaCarOn", 
  farobot: "FaRobot",
  famagnifyingglass: "FaMagnifyingGlass",
  fagift: "FaGift",
  fafileinvoicedollar: "FaFileInvoiceDollar",
  faheart: "FaHeart",
  falistcheck: "FaListCheck",
  faglobe: "FaGlobe",
  falandmarkdome: "FaLandmarkDome",
  faleaf: "FaLeaf",
  fausershield: "FaUserShield",
  fayoutube: "FaYoutube",
  fabookuser: "FaBookUser", 

  // StickyChat specific icons if they are different or need aliases
  faarrowright: "FaArrowRight",
  fahighlighter: "FaHighlighter",
  fagithub: "FaGithub",
  fadownload: "FaDownload",
  facode: "FaCode",
  facommentdots: "FaCommentDots",
  fapaperplane: "FaPaperPlane",
  falightbulb: "FaLightbulb", 
  faimages: "FaImages",
  fasquarearrowupright: "FaSquareArrowUpRight",
  fafileimport: "FaFileImport",
  faclipboardlist: "FaClipboardList",
  facirclecheck: "FaCircleCheck",
  faicons: "FaIcons", 
  faspinner: "FaSpinner",

  // Tutorial Inception Specific
  // fauniversalaccess: "FaUniversalAccess", // Already covered
  // fafire: "FaFire",                   // Already covered
  // fasatellitedish: "FaSatelliteDish",   // Already covered
  // falaptopcode: "FaLaptopCode",        // Already covered

  // Error and diagnostics related
  favial: "FaVial",
  fadatabase: "FaDatabase",
  faboxarchive: "FaBoxArchive",
  facoins: "FaCoins",
  fakraken: "FaKraken", 
  facodecommit: "FaCodeCommit",
  fatree: "FaTree",
  faplus: "FaPlus",
  fabroom: "FaBroom",
  fascroll: "FaScroll",
  famobilescreenbutton: "FaMobileScreenButton",
  fauserdoctor: "FaUserDoctor",
  fapuzzlepiece: "FaPuzzlePiece",
  falayergroup: "FaLayerGroup",
};