import type * as Fa6Icons from "react-icons/fa6";

export const iconNameMap: { [key: string]: keyof typeof Fa6Icons } = {
  // General & UI
  fathumbsup: "FaThumbsUp",
  faeye: "FaEye",
  fakeyboard: "FaKeyboard",
  fawandmagicsparkles: "FaWandMagicSparkles",
  facheckdouble: "FaCheckDouble",
  fatools: "FaToolbox",
  facodebranch: "FaCodeBranch",
  falandmineon: "FaLandMineOn",
  fascrewdriverwrench: "FaScrewdriverWrench",
  fasmilewink: "FaSmileWink",
  fatriangleexclamation: "FaTriangleExclamation",
  facrosshairs: "FaCrosshairs",
  fabookmedical: "FaBookMedical",
  fashieldhalved: "FaShieldHalved",
  faaward: "FaAward",
  fabookopen: "FaBookOpen",
  fabrain: "FaBrain",
  fainfinity: "FaInfinity",
  farecycle: "FaRecycle",
  fashapes: "FaShapes",
  fahammer: "FaHammer",
  faprojectdiagram: "FaProjectDiagram",
  fabroadcasttower: "FaBroadcastTower",
  fauniversalaccess: "FaUniversalAccess",
  fabong: "FaBong",
  fafire: "FaFire",
  fasatellitedish: "FaSatelliteDish",
  falaptopcode: "FaLaptopCode",
  fatoolbox: "FaToolbox",
  falink: "FaLink",
  faupload: "FaUpload",
  facheck: "FaCheck",
  faexchangealt: "FaExchangeAlt",
  faimageslash: "FaImageSlash",
  faimageportrait: "FaImagePortrait",
  faplaycircle: "FaPlayCircle",
  faexternallinkalt: "FaExternalLinkAlt",
  fabomb: "FaBomb",
  famedal: "FaMedal",
  favideo: "FaVideo",
  favideoslash: "FaVideoSlash",
  fafilm: "FaFilm",
  faroad: "FaRoad",
  fauserninja: "FaUserNinja",
  fagamepad: "FaGamepad",
  facircleuser: "FaCircleUser",
  facreditcard: "FaCreditCard",
  fastar: "FaStar",
  fagears: "FaGears",
  fausers: "FaUsers",
  farocket: "FaRocket",
  fanetworkwired: "FaNetworkWired",
  fareglightbulb: "FaRegLightbulb",
  fapalette: "FaPalette",
  facircleinfo: "FaCircleInfo",
  fadollarsign: "FaDollarSign",
  facaron: "FaCarOn",
  farobot: "FaRobot",
  famagnifyingglass: "FaMagnifyingGlass",
  fagift: "FaGift",
  fafileinvoicedollar: "FaFileInvoiceDollar",
  faheart: "FaHeart",
  falistcheck: "FaListCheck",
  faglobe: "FaGlobe",
  falandmarkdome: "FaLandmarkDome",
  faleaf: "FaLeaf",
  fausershield: "FaUserShield",
  fayoutube: "FaYoutube",
  fabookuser: "FaBookUser",
  fabolt: "FaBolt",
  fakey: "FaKey",
  fadooropen: "FaDoorOpen",
  faregcopy: "FaRegCopy",
  fapaste: "FaPaste",
  famagic: "FaWandMagicSparkles", // Duplicate, but same mapping is fine
  facheckcircle: "FaCheckCircle",
  facrown: "FaCrown",
  facopy: "FaCopy",
  faclouduploadalt: "FaCloudUploadAlt",
  faforwardstep: "FaForwardStep",
  faserver: "FaServer",
  faphotofilm: "FaPhotoFilm",
  favideocamera: "FaVideoCamera",
  fapoostorm: "FaPooStorm",
  fabook: "FaBook",
  fabiohazard: "FaBiohazard",
  fameteor: "FaMeteor",
  fadumbbell: "FaDumbbell",
  fafistraised: "FaFistRaised",
  fastreetview: "FaStreetView",
  fahandmiddlefinger: "FaHandMiddleFinger",
  facity: "FaCity",
  faangledoubledown: "FaAngleDoubleDown",
  faguitar: "FaGuitar",

  // StickyChat specific icons (many might be duplicates, ensure correct Fa6 mapping)
  faarrowright: "FaArrowRight",
  fahighlighter: "FaHighlighter",
  fagithub: "FaGithub",
  fadownload: "FaDownload",
  facode: "FaCode",
  facommentdots: "FaCommentDots",
  fapaperplane: "FaPaperPlane",
  falightbulb: "FaLightbulb",
  faimages: "FaImages",
  fasquarearrowupright: "FaSquareArrowUpRight", // Maps to FaSquareArrowUpRight
  fafileimport: "FaFileImport",
  faclipboardlist: "FaClipboardList",
  faicons: "FaIcons",
  faspinner: "FaSpinner",

  // Error and diagnostics related
  favial: "FaVial",
  fadatabase: "FaDatabase",
  faboxarchive: "FaBoxArchive",
  facoins: "FaCoins",
  fakraken: "FaKraken",
  facodecommit: "FaCodeCommit",
  fatree: "FaTree",
  faplus: "FaPlus",
  fabroom: "FaBroom",
  fascroll: "FaScroll",
  famobilescreenbutton: "FaMobileScreenButton",
  fauserdoctor: "FaUserDoctor",
  fapuzzlepiece: "FaPuzzlePiece",
  falayergroup: "FaLayerGroup",
  fagraduationcap: "FaGraduationCap",
  fauplong: "FaUpLong",
  faheartbeat: "FaHeartbeat",

  // From PR description / repo-xml page.tsx / ActualPageContent
  faangleup: "FaAngleUp",
  faangledown: "FaAngleDown",
  faxmarkcircle: "FaXmarkCircle", // maps to FaCircleXmark or FaXmarkCircle
  fafile: "FaFile",
  fafolder: "FaFolder",
  faterminal: "FaTerminal",
  facloud: "FaCloud",
  fahandsparkles: "FaHandSparkles",
  faarrowuprightfromsquare: "FaArrowUpRightFromSquare",
  fauserastronaut: "FaUserAstronaut",
  fabullseye: "FaBullseye",
  faatom: "FaAtom",
  fabug: "FaBug",
  famicrophone: "FaMicrophone",
  famemory: "FaMemory",
  fabriefcase: "FaBriefcase",
  famagnifyingglasschart: "FaMagnifyingGlassChart",
  faquoteleft: "FaQuoteLeft",
  faquoteright: "FaQuoteRight",
  facirclexmark: "FaCircleXmark", // Same as faxmarkcircle if it maps to this
  faanglesdown: "FaAnglesDown",
  faanglesup: "FaAnglesUp",
  
  // From AutomationBuddy
  faarrowsrotate: "FaArrowsRotate",
  faangrycreative: "FaAngrycreative", // Check if this exists in Fa6, might need alternative
  fapoo: "FaPoo",
  falist: "FaList",
  faexclamation: "FaExclamationTriangle", // FaExclamation does not exist, FaExclamationTriangle is common
  
  // From AICodeAssistant
  fafilelines: "FaFileLines",

  // From RepoTxtFetcher (some might be duplicates)
  faarrowsrotaterepotxt: "FaArrowsRotate", // if specific styling needed, else use faarrowsrotate
  
  // Ensure all icons from VibeContentRenderer in repo-xml/page.tsx are here
  // Example: If <VibeContentRenderer content="::FaRocket::" /> is used, 'farocket' should be in this map.
  // Checked: FaDownload, FaCircleInfo, FaGithub, FaWandMagicSparkles, FaUpLong, FaHandSparkles,
  // FaArrowUpRightFromSquare, FaUserAstronaut, FaHeart, FaBullseye, FaAtom, FaBrain,
  // FaCodeBranch, FaPlus, FaCopy, FaSpinner, FaBolt, FaToolbox, FaCode, FaVideo,
  // FaDatabase, FaBug, FaMicrophone, FaLink, FaServer, FaRocket, FaMagnifyingGlass,
  // FaMemory, FaKeyboard, FaBriefcase, FaMagnifyingGlassChart, FaTree, FaEye, FaUsers,
  // FaQuoteLeft, FaQuoteRight, FaCircleXmark, FaAnglesDown, FaAnglesUp, FaVideoSlash

  // If any icon was used like <FaSpecificIcon directly, ensure its 'faspecificicon' key is here.
  // e.g. for <FaRocket />, ensure 'farocket': 'FaRocket' is present. (It is)
};