import { NextResponse } from "next/server";
import { supabaseAdmin } from "@/lib/supabase-server";

/**
 * Daily Insights Cron Endpoint
 *
 * Called by Supabase pg_cron to generate and send daily rent/sale contract summary.
 * Secured by CRON_SECRET environment variable.
 *
 * Supabase SQL to schedule:
 *
 *   CREATE EXTENSION IF NOT EXISTS pg_cron;
 *
 *   SELECT cron.schedule(
 *     'daily-insights',
 *     '0 21 * * *',  -- 9 PM daily
 *     $$
 *     SELECT net.http_post(
 *       url := 'https://v0-car-test.vercel.app/api/cron/daily-insights',
 *       headers := jsonb_build_object(
 *         'Content-Type', 'application/json',
 *         'Authorization', 'Bearer ' || current_setting('app.settings.cron_secret', true)
 *       ),
 *       body := '{}'::jsonb
 *     );
 *     $$
 *   );
 */

export async function POST(request: Request) {
  // Verify cron secret for security
  const authHeader = request.headers.get("authorization");
  const cronSecretHeader = request.headers.get("x-cron-secret");
  const cronSecret = process.env.CRON_SECRET || process.env.CODEX_BRIDGE_CALLBACK_SECRET;

  // Check both Authorization header and x-cron-secret header
  const providedSecret = authHeader?.replace("Bearer ", "") || cronSecretHeader;

  if (!cronSecret) {
    console.error("[daily-insights] CRON_SECRET not configured");
    return NextResponse.json(
      { error: "Server configuration error" },
      { status: 500 }
    );
  }

  if (providedSecret !== cronSecret) {
    console.warn("[daily-insights] Unauthorized access attempt");
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    const today = new Date().toISOString().split("T")[0];

    // Support optional crew_slug filter from request body (or query param)
    const body: { crew_slug?: string } = await request.json().catch(() => ({}));
    const crewSlugFilter = body.crew_slug;

    // Build base query with optional crew_slug filter
    const buildContractQuery = (table: string) => {
      let query = supabaseAdmin.from(table as any).select("*").gte("created_at", today);
      if (crewSlugFilter) {
        query = query.eq("crew_slug", crewSlugFilter);
      }
      return query.order("created_at", { ascending: false });
    };

    // Get today's rental contracts from rental_contract_artifacts
    // These are contracts generated by the /doc rent flow
    const { data: rentalContracts, error: rentalsError } = await buildContractQuery("rental_contract_artifacts");

    if (rentalsError) {
      console.error("[daily-insights] Rental contracts query error:", rentalsError);
    }

    // Get today's sale contracts from private.sale_contract_artifacts
    // These are contracts generated by the /doc sale flow
    const { data: saleContracts, error: salesError } = await buildContractQuery("sale_contract_artifacts");

    if (salesError) {
      console.error("[daily-insights] Sale contracts query error:", salesError);
    }

    // Calculate rental summary
    let rentalCount = rentalContracts?.length || 0;
    let rentalSum = 0;

    // For rentals, total_sum may not be populated, so we try to get from bikes
    if (rentalContracts && rentalContracts.length > 0) {
      for (const contract of rentalContracts) {
        if (contract.total_sum) {
          rentalSum += Number(contract.total_sum);
        } else if (contract.resolved_bike_id) {
          // Try to get price from bikes table
          const { data: bike } = await supabaseAdmin
            .from("cars")
            .select("daily_price, specs")
            .eq("id", contract.resolved_bike_id)
            .maybeSingle();

          if (bike) {
            // Use price_rub from specs if available, otherwise daily_price
            const priceFromSpec = bike.specs?.price_rub
              ? Number(bike.specs.price_rub)
              : bike.daily_price
              ? Number(bike.daily_price)
              : 0;
            rentalSum += priceFromSpec;
          }
        }
      }
    }

    // Calculate sale summary
    let saleCount = saleContracts?.length || 0;
    let saleSum = 0;

    if (saleContracts && saleContracts.length > 0) {
      for (const contract of saleContracts) {
        if (contract.total_sum) {
          saleSum += Number(contract.total_sum);
        } else if (contract.sale_price) {
          // Parse sale_price (remove spaces and convert to number)
          const parsedPrice = contract.sale_price.replace(/\s/g, "");
          saleSum += Number(parsedPrice) || 0;
        }
      }
    }

    const totalSum = rentalSum + saleSum;

    // Build summary message
    let message = `📊 <b>Daily Contract Insights</b> — ${new Date().toLocaleDateString('ru-RU')} (9 PM)\n\n`;
    message += `🛵 <b>Rental Contracts:</b> ${rentalCount}\n`;
    if (rentalCount > 0) {
      message += `   💰 Total: ${rentalSum.toLocaleString('ru-RU')} ₽\n`;
    }
    message += `\n🏍️ <b>Sale Contracts:</b> ${saleCount}\n`;
    if (saleCount > 0) {
      message += `   💰 Total: ${saleSum.toLocaleString('ru-RU')} ₽\n`;
    }
    message += `\n💎 <b>Total Contract Value: ${totalSum.toLocaleString('ru-RU')} ₽</b>\n`;

    // Add extras section if there are contracts
    if (rentalCount > 0 || saleCount > 0) {
      message += `\n━━━━━━━━━━━━━━━━━━\n📋 <b>Contract Details:</b>\n\n`;

      // List rental contracts
      if (rentalCount > 0 && rentalContracts) {
        message += `<b>Rental Contracts (${rentalCount}):</b>\n`;
        for (const contract of rentalContracts.slice(0, 5)) {
          const value = contract.total_sum
            ? Number(contract.total_sum).toLocaleString('ru-RU')
            : contract.resolved_bike_id || 'N/A';
          message += `📄 ${contract.renter_full_name || 'Unknown'} — ${value} ₽\n`;
        }
        if (rentalContracts.length > 5) {
          message += `   ... и ещё ${rentalContracts.length - 5}\n`;
        }
        message += `\n`;
      }

      // List sale contracts
      if (saleCount > 0 && saleContracts) {
        message += `<b>Sale Contracts (${saleCount}):</b>\n`;
        for (const contract of saleContracts.slice(0, 5)) {
          const value = contract.total_sum
            ? Number(contract.total_sum).toLocaleString('ru-RU')
            : contract.sale_price || 'N/A';
          message += `📄 ${contract.buyer_full_name || 'Unknown'} — ${value} ₽\n`;
        }
        if (saleContracts.length > 5) {
          message += `   ... и ещё ${saleContracts.length - 5}\n`;
        }
      }
    }

    // Add note if no contracts today
    if (rentalCount === 0 && saleCount === 0) {
      message += `\n📭 No contracts generated today. The bot is resting.`;
    }

    // Send via forward-telegram API
    const adminChatId = process.env.ADMIN_CHAT_ID;
    if (!adminChatId) {
      console.error("[daily-insights] ADMIN_CHAT_ID not configured");
      return NextResponse.json(
        { error: "Server configuration error" },
        { status: 500 }
      );
    }

    const telegramResponse = await fetch(
      `${process.env.NEXT_PUBLIC_SITE_URL}/api/forward-telegram`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          chat_id: adminChatId,
          method: "sendMessage",
          payload: {
            text: message,
            parse_mode: "HTML",
          },
        }),
      }
    );

    if (!telegramResponse.ok) {
      const errorText = await telegramResponse.text();
      console.error(
        "[daily-insights] Telegram API error:",
        telegramResponse.status,
        errorText
      );
      throw new Error(`Telegram API failed: ${errorText}`);
    }

    const summary = {
      date: today,
      rentals: { count: rentalCount, total_sum: rentalSum },
      sales: { count: saleCount, total_sum: saleSum },
      total: totalSum,
    };

    console.log("[daily-insights] Daily contract insights sent successfully:", summary);
    return NextResponse.json({ success: true, summary });
  } catch (error) {
    console.error("[daily-insights] Error:", error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Unknown error" },
      { status: 500 }
    );
  }
}
