"use client";

import React, { MutableRefObject, ChangeEventHandler } from 'react';
import { motion } from 'framer-motion';
import { FaClipboard, FaBroom, FaRobot, FaPlus, FaFileLines, FaArrowsRotate } from 'react-icons/fa6'; // Added FaFileLines, FaArrowsRotate
import { toast } from 'sonner'; // Import toast

interface RequestInputProps {
    kworkInputRef: MutableRefObject<HTMLTextAreaElement | null>;
    onCopyToClipboard: () => void;
    onClearAll: () => void;
    isCopyDisabled: boolean;
    isClearDisabled: boolean;
    onInputChange?: (value: string) => void; // Optional callback for parent
    initialValue?: string; // Optional initial value
    // New props for Ask AI button
    // === FIX: Correct the expected return type for onAskAi ===
    onAskAi: () => Promise<{ success: boolean; requestId?: string; error?: string }>; // Changed from Promise<void>
    isAskAiDisabled: boolean;
    aiActionLoading: boolean;
    // New prop for Add Selected
    onAddSelected: (autoAsk?: boolean) => Promise<void>;
    isAddSelectedDisabled: boolean;
    selectedFetcherFilesCount: number;
}

// Instructions text constant
const BOT_INSTRUCTIONS = `Wassup, fella vibe coding enthusiast! We are vibing next level selfevolving vibe dev platform oneSitePls - it's telegram bot has a full fledged web app with a lot of working outofthebox stuff, all boilerplate with, telegram auth, supabase, storage and one special automagic thing - repo-xml page, which allows to extract github project files into context for request to dev bot, whose reply can be copied in full in parsed back into Pull Request which can be then merged in 1 click and update production in a minute:) OR you can extract files from branch from PR and continue iterating by parsing and pushing back to PR's branch, think on this next level always;)

Also try to:
- don't skip code (skip whole file if unchanged)
- mark "// .." comments with two dots for comments if you want, but use three dots only in skipped parts markers - i detect such issues during response parsing to reask for full version, no problem;)
- first line of code in each file must be comment with path like "// /components/comp1.tsx" for example
- first line of response is kinda important too - it will be parsed out into PR title, so try not to start response with generick phrases like "okey, lets do it" as my PR list only shows first like 50 symbols, make them  explicitly telling. And next couple of chapters please describe changes in russian, they will be visible in notification;)
- don't use fa icons (use fa6), and especially avoid FaTimesCircle and FaCog (use FaBranch instead of FaCog, make sure icon exists, use following complete list to doublecheck as i hate these errors:) NO FaUserCircle - there is FaCircleUser, and FaMapLocation instead of FaMapSigns):
Fa42Group
Fa500Px
FaAccessibleIcon
FaAccusoft
FaAdn
FaAdversal
FaAffiliatetheme
FaAirbnb
FaAlgolia
FaAlipay
FaAmazonPay
FaAmazon
FaAmilia
FaAndroid
FaAngellist
FaAngrycreative
FaAngular
FaAppStoreIos
FaAppStore
FaApper
FaApplePay
FaApple
FaArtstation
FaAsymmetrik
FaAtlassian
FaAudible
FaAutoprefixer
FaAvianex
FaAviato
FaAws
FaBandcamp
FaBattleNet
FaBehance
FaBilibili
FaBimobject
FaBitbucket
FaBitcoin
FaBity
FaBlackTie
FaBlackberry
FaBloggerB
FaBlogger
FaBluetoothB
FaBluetooth
FaBootstrap
FaBots
FaBtc
FaBuffer
FaBuromobelexperte
FaBuyNLarge
FaBuysellads
FaCanadianMapleLeaf
FaCcAmazonPay
FaCcAmex
FaCcApplePay
FaCcDinersClub
FaCcDiscover
FaCcJcb
FaCcMastercard
FaCcPaypal
FaCcStripe
FaCcVisa
FaCentercode
FaCentos
FaChrome
FaChromecast
FaCloudflare
FaCloudscale
FaCloudsmith
FaCloudversify
FaCmplid
FaCodepen
FaCodiepie
FaConfluence
FaConnectdevelop
FaContao
FaCottonBureau
FaCpanel
FaCreativeCommonsBy
FaCreativeCommonsNcEu
FaCreativeCommonsNcJp
FaCreativeCommonsNc
FaCreativeCommonsNd
FaCreativeCommonsPdAlt
FaCreativeCommonsPd
FaCreativeCommonsRemix
FaCreativeCommonsSa
FaCreativeCommonsSamplingPlus
FaCreativeCommonsSampling
FaCreativeCommonsShare
FaCreativeCommonsZero
FaCreativeCommons
FaCriticalRole
FaCss3Alt
FaCss3
FaCuttlefish
FaDAndDBeyond
FaDAndD
FaDailymotion
FaDashcube
FaDebian
FaDeezer
FaDelicious
FaDeploydog
FaDeskpro
FaDev
FaDeviantart
FaDhl
FaDiaspora
FaDigg
FaDigitalOcean
FaDiscord
FaDiscourse
FaDochub
FaDocker
FaDraft2Digital
FaDribbble
FaDropbox
FaDrupal
FaDyalog
FaEarlybirds
FaEbay
FaEdgeLegacy
FaEdge
FaElementor
FaEllo
FaEmber
FaEmpire
FaEnvira
FaErlang
FaEthereum
FaEtsy
FaEvernote
FaExpeditedssl
FaFacebookF
FaFacebookMessenger
FaFacebook
FaFantasyFlightGames
FaFedex
FaFedora
FaFigma
FaFirefoxBrowser
FaFirefox
FaFirstOrderAlt
FaFirstOrder
FaFirstdraft
FaFlickr
FaFlipboard
FaFly
FaFontAwesome
FaFonticonsFi
FaFonticons
FaFortAwesomeAlt
FaFortAwesome
FaForumbee
FaFoursquare
FaFreeCodeCamp
FaFreebsd
FaFulcrum
FaGalacticRepublic
FaGalacticSenate
FaGetPocket
FaGgCircle
FaGg
FaGitAlt
FaGit
FaGithubAlt
FaGithub
FaGitkraken
FaGitlab
FaGitter
FaGlideG
FaGlide
FaGofore
FaGolang
FaGoodreadsG
FaGoodreads
FaGoogleDrive
FaGooglePay
FaGooglePlay
FaGooglePlusG
FaGooglePlus
FaGoogleWallet
FaGoogle
FaGratipay
FaGrav
FaGripfire
FaGrunt
FaGuilded
FaGulp
FaHackerNews
FaHackerrank
FaHashnode
FaHips
FaHireAHelper
FaHive
FaHooli
FaHornbill
FaHotjar
FaHouzz
FaHtml5
FaHubspot
FaIdeal
FaImdb
FaInstagram
FaInstalod
FaIntercom
FaInternetExplorer
FaInvision
FaIoxhost
FaItchIo
FaItunesNote
FaItunes
FaJava
FaJediOrder
FaJenkins
FaJira
FaJoget
FaJoomla
FaJs
FaJsfiddle
FaKaggle
FaKeybase
FaKeycdn
FaKickstarterK
FaKickstarter
FaKorvue
FaLaravel
FaLastfm
FaLeanpub
FaLess
FaLine
FaLinkedinIn
FaLinkedin
FaLinode
FaLinux
FaLyft
FaMagento
FaMailchimp
FaMandalorian
FaMarkdown
FaMastodon
FaMaxcdn
FaMdb
FaMedapps
FaMedium
FaMedrt
FaMeetup
FaMegaport
FaMendeley
FaMeta
FaMicroblog
FaMicrosoft
FaMix
FaMixcloud
FaMixer
FaMizuni
FaModx
FaMonero
FaNapster
FaNeos
FaNfcDirectional
FaNfcSymbol
FaNimblr
FaNodeJs
FaNode
FaNpm
FaNs8
FaNutritionix
FaOctopusDeploy
FaOdnoklassniki
FaOdysee
FaOldRepublic
FaOpencart
FaOpenid
FaOpera
FaOptinMonster
FaOrcid
FaOsi
FaPadlet
FaPage4
FaPagelines
FaPalfed
FaPatreon
FaPaypal
FaPerbyte
FaPeriscope
FaPhabricator
FaPhoenixFramework
FaPhoenixSquadron
FaPhp
FaPiedPiperAlt
FaPiedPiperHat
FaPiedPiperPp
FaPiedPiper
FaPinterestP
FaPinterest
FaPix
FaPlaystation
FaProductHunt
FaPushed
FaPython
FaQq
FaQuinscape
FaQuora
FaRProject
FaRaspberryPi
FaRavelry
FaReact
FaReacteurope
FaReadme
FaRebel
FaRedRiver
FaRedditAlien
FaReddit
FaRedhat
FaRenren
FaReplyd
FaResearchgate
FaResolving
FaRev
FaRocketchat
FaRockrms
FaRust
FaSafari
FaSalesforce
FaSass
FaSchlix
FaScreenpal
FaScribd
FaSearchengin
FaSellcast
FaSellsy
FaServicestack
FaShirtsinbulk
FaShopify
FaShopware
FaSimplybuilt
FaSistrix
FaSith
FaSitrox
FaSketch
FaSkyatlas
FaSkype
FaSlack
FaSlideshare
FaSnapchat
FaSoundcloud
FaSourcetree
FaSpaceAwesome
FaSpeakap
FaSpeakerDeck
FaSpotify
FaSquareBehance
FaSquareDribbble
FaSquareFacebook
FaSquareFontAwesomeStroke
FaSquareFontAwesome
FaSquareGit
FaSquareGithub
FaSquareGitlab
FaSquareGooglePlus
FaSquareHackerNews
FaSquareInstagram
FaSquareJs
FaSquareLastfm
FaSquareOdnoklassniki
FaSquarePiedPiper
FaSquarePinterest
FaSquareReddit
FaSquareSnapchat
FaSquareSteam
FaSquareThreads
FaSquareTumblr
FaSquareTwitter
FaSquareViadeo
FaSquareVimeo
FaSquareWhatsapp
FaSquareXTwitter
FaSquareXing
FaSquareYoutube
FaSquarespace
FaStackExchange
FaStackOverflow
FaStackpath
FaStaylinked
FaSteamSymbol
FaSteam
FaStickerMule
FaStrava
FaStripeS
FaStripe
FaStubber
FaStudiovinari
FaStumbleuponCircle
FaStumbleupon
FaSuperpowers
FaSupple
FaSuse
FaSwift
FaSymfony
FaTeamspeak
FaTelegram
FaTencentWeibo
FaTheRedYeti
FaThemeco
FaThemeisle
FaThinkPeaks
FaThreads
FaTiktok
FaTradeFederation
FaTrello
FaTumblr
FaTwitch
FaTwitter
FaTypo3
FaUber
FaUbuntu
FaUikit
FaUmbraco
FaUncharted
FaUniregistry
FaUnity
FaUnsplash
FaUntappd
FaUps
FaUsb
FaUsps
FaUssunnah
FaVaadin
FaViacoin
FaViadeo
FaViber
FaVimeoV
FaVimeo
FaVine
FaVk
FaVnv
FaVuejs
FaWatchmanMonitoring
FaWaze
FaWeebly
FaWeibo
FaWeixin
FaWhatsapp
FaWhmcs
FaWikipediaW
FaWindows
FaWirsindhandwerk
FaWix
FaWizardsOfTheCoast
FaWodu
FaWolfPackBattalion
FaWordpressSimple
FaWordpress
FaWpbeginner
FaWpexplorer
FaWpforms
FaWpressr
FaXTwitter
FaXbox
FaXing
FaYCombinator
FaYahoo
FaYammer
FaYandexInternational
FaYandex
FaYarn
FaYelp
FaYoast
FaYoutube
FaZhihu
Fa0
Fa1
Fa2
Fa3
Fa4
Fa5
Fa6
Fa7
Fa8
Fa9
FaA
FaAddressBook
FaAddressCard
FaAlignCenter
FaAlignJustify
FaAlignLeft
FaAlignRight
FaAnchorCircleCheck
FaAnchorCircleExclamation
FaAnchorCircleXmark
FaAnchorLock
FaAnchor
FaAngleDown
FaAngleLeft
FaAngleRight
FaAngleUp
FaAnglesDown
FaAnglesLeft
FaAnglesRight
FaAnglesUp
FaAnkh
FaAppleWhole
FaArchway
FaArrowDown19
FaArrowDown91
FaArrowDownAZ
FaArrowDownLong
FaArrowDownShortWide
FaArrowDownUpAcrossLine
FaArrowDownUpLock
FaArrowDownWideShort
FaArrowDownZA
FaArrowDown
FaArrowLeftLong
FaArrowLeft
FaArrowPointer
FaArrowRightArrowLeft
FaArrowRightFromBracket
FaArrowRightLong
FaArrowRightToBracket
FaArrowRightToCity
FaArrowRight
FaArrowRotateLeft
FaArrowRotateRight
FaArrowTrendDown
FaArrowTrendUp
FaArrowTurnDown
FaArrowTurnUp
FaArrowUp19
FaArrowUp91
FaArrowUpAZ
FaArrowUpFromBracket
FaArrowUpFromGroundWater
FaArrowUpFromWaterPump
FaArrowUpLong
FaArrowUpRightDots
FaArrowUpRightFromSquare
FaArrowUpShortWide
FaArrowUpWideShort
FaArrowUpZA
FaArrowUp
FaArrowsDownToLine
FaArrowsDownToPeople
FaArrowsLeftRightToLine
FaArrowsLeftRight
FaArrowsRotate
FaArrowsSpin
FaArrowsSplitUpAndLeft
FaArrowsToCircle
FaArrowsToDot
FaArrowsToEye
FaArrowsTurnRight
FaArrowsTurnToDots
FaArrowsUpDownLeftRight
FaArrowsUpDown
FaArrowsUpToLine
FaAsterisk
FaAt
FaAtom
FaAudioDescription
FaAustralSign
FaAward
FaB
FaBabyCarriage
FaBaby
FaBackwardFast
FaBackwardStep
FaBackward
FaBacon
FaBacteria
FaBacterium
FaBagShopping
FaBahai
FaBahtSign
FaBanSmoking
FaBan
FaBandage
FaBangladeshiTakaSign
FaBarcode
FaBarsProgress
FaBarsStaggered
FaBars
FaBaseballBatBall
FaBaseball
FaBasketShopping
FaBasketball
FaBath
FaBatteryEmpty
FaBatteryFull
FaBatteryHalf
FaBatteryQuarter
FaBatteryThreeQuarters
FaBedPulse
FaBed
FaBeerMugEmpty
FaBellConcierge
FaBellSlash
FaBell
FaBezierCurve
FaBicycle
FaBinoculars
FaBiohazard
FaBitcoinSign
FaBlenderPhone
FaBlender
FaBlog
FaBold
FaBoltLightning
FaBolt
FaBomb
FaBone
FaBong
FaBookAtlas
FaBookBible
FaBookBookmark
FaBookJournalWhills
FaBookMedical
FaBookOpenReader
FaBookOpen
FaBookQuran
FaBookSkull
FaBookTanakh
FaBook
FaBookmark
FaBorderAll
FaBorderNone
FaBorderTopLeft
FaBoreHole
FaBottleDroplet
FaBottleWater
FaBowlFood
FaBowlRice
FaBowlingBall
FaBoxArchive
FaBoxOpen
FaBoxTissue
FaBox
FaBoxesPacking
FaBoxesStacked
FaBraille
FaBrain
FaBrazilianRealSign
FaBreadSlice
FaBridgeCircleCheck
FaBridgeCircleExclamation
FaBridgeCircleXmark
FaBridgeLock
FaBridgeWater
FaBridge
FaBriefcaseMedical
FaBriefcase
FaBroomBall
FaBroom
FaBrush
FaBucket
FaBugSlash
FaBug
FaBugs
FaBuildingCircleArrowRight
FaBuildingCircleCheck
FaBuildingCircleExclamation
FaBuildingCircleXmark
FaBuildingColumns
FaBuildingFlag
FaBuildingLock
FaBuildingNgo
FaBuildingShield
FaBuildingUn
FaBuildingUser
FaBuildingWheat
FaBuilding
FaBullhorn
FaBullseye
FaBurger
FaBurst
FaBusSimple
FaBus
FaBusinessTime
FaC
FaCableCar
FaCakeCandles
FaCalculator
FaCalendarCheck
FaCalendarDay
FaCalendarDays
FaCalendarMinus
FaCalendarPlus
FaCalendarWeek
FaCalendarXmark
FaCalendar
FaCameraRetro
FaCameraRotate
FaCamera
FaCampground
FaCandyCane
FaCannabis
FaCapsules
FaCarBattery
FaCarBurst
FaCarOn
FaCarRear
FaCarSide
FaCarTunnel
FaCar
FaCaravan
FaCaretDown
FaCaretLeft
FaCaretRight
FaCaretUp
FaCarrot
FaCartArrowDown
FaCartFlatbedSuitcase
FaCartFlatbed
FaCartPlus
FaCartShopping
FaCashRegister
FaCat
FaCediSign
FaCentSign
FaCertificate
FaChair
FaChalkboardUser
FaChalkboard
FaChampagneGlasses
FaChargingStation
FaChartArea
FaChartBar
FaChartColumn
FaChartGantt
FaChartLine
FaChartPie
FaChartSimple
FaCheckDouble
FaCheckToSlot
FaCheck
FaCheese
FaChessBishop
FaChessBoard
FaChessKing
FaChessKnight
FaChessPawn
FaChessQueen
FaChessRook
FaChess
FaChevronDown
FaChevronLeft
FaChevronRight
FaChevronUp
FaChildCombatant
FaChildDress
FaChildReaching
FaChild
FaChildren
FaChurch
FaCircleArrowDown
FaCircleArrowLeft
FaCircleArrowRight
FaCircleArrowUp
FaCircleCheck
FaCircleChevronDown
FaCircleChevronLeft
FaCircleChevronRight
FaCircleChevronUp
FaCircleDollarToSlot
FaCircleDot
FaCircleDown
FaCircleExclamation
FaCircleH
FaCircleHalfStroke
FaCircleInfo
FaCircleLeft
FaCircleMinus
FaCircleNodes
FaCircleNotch
FaCirclePause
FaCirclePlay
FaCirclePlus
FaCircleQuestion
FaCircleRadiation
FaCircleRight
FaCircleStop
FaCircleUp
FaCircleUser
FaCircleXmark
FaCircle
FaCity
FaClapperboard
FaClipboardCheck
FaClipboardList
FaClipboardQuestion
FaClipboardUser
FaClipboard
FaClockRotateLeft
FaClock
FaClone
FaClosedCaptioning
FaCloudArrowDown
FaCloudArrowUp
FaCloudBolt
FaCloudMeatball
FaCloudMoonRain
FaCloudMoon
FaCloudRain
FaCloudShowersHeavy
FaCloudShowersWater
FaCloudSunRain
FaCloudSun
FaCloud
FaClover
FaCodeBranch
FaCodeCommit
FaCodeCompare
FaCodeFork
FaCodeMerge
FaCodePullRequest
FaCode
FaCoins
FaColonSign
FaCommentDollar
FaCommentDots
FaCommentMedical
FaCommentSlash
FaCommentSms
FaComment
FaCommentsDollar
FaComments
FaCompactDisc
FaCompassDrafting
FaCompass
FaCompress
FaComputerMouse
FaComputer
FaCookieBite
FaCookie
FaCopy
FaCopyright
FaCouch
FaCow
FaCreditCard
FaCropSimple
FaCrop
FaCross
FaCrosshairs
FaCrow
FaCrown
FaCrutch
FaCruzeiroSign
FaCube
FaCubesStacked
FaCubes
FaD
FaDatabase
FaDeleteLeft
FaDemocrat
FaDesktop
FaDharmachakra
FaDiagramNext
FaDiagramPredecessor
FaDiagramProject
FaDiagramSuccessor
FaDiamondTurnRight
FaDiamond
FaDiceD20
FaDiceD6
FaDiceFive
FaDiceFour
FaDiceOne
FaDiceSix
FaDiceThree
FaDiceTwo
FaDice
FaDisease
FaDisplay
FaDivide
FaDna
FaDog
FaDollarSign
FaDolly
FaDongSign
FaDoorClosed
FaDoorOpen
FaDove
FaDownLeftAndUpRightToCenter
FaDownLong
FaDownload
FaDragon
FaDrawPolygon
FaDropletSlash
FaDroplet
FaDrumSteelpan
FaDrum
FaDrumstickBite
FaDumbbell
FaDumpsterFire
FaDumpster
FaDungeon
FaE
FaEarDeaf
FaEarListen
FaEarthAfrica
FaEarthAmericas
FaEarthAsia
FaEarthEurope
FaEarthOceania
FaEgg
FaEject
FaElevator
FaEllipsisVertical
FaEllipsis
FaEnvelopeCircleCheck
FaEnvelopeOpenText
FaEnvelopeOpen
FaEnvelope
FaEnvelopesBulk
FaEquals
FaEraser
FaEthernet
FaEuroSign
FaExclamation
FaExpand
FaExplosion
FaEyeDropper
FaEyeLowVision
FaEyeSlash
FaEye
FaF
FaFaceAngry
FaFaceDizzy
FaFaceFlushed
FaFaceFrownOpen
FaFaceFrown
FaFaceGrimace
FaFaceGrinBeamSweat
FaFaceGrinBeam
FaFaceGrinHearts
FaFaceGrinSquintTears
FaFaceGrinSquint
FaFaceGrinStars
FaFaceGrinTears
FaFaceGrinTongueSquint
FaFaceGrinTongueWink
FaFaceGrinTongue
FaFaceGrinWide
FaFaceGrinWink
FaFaceGrin
FaFaceKissBeam
FaFaceKissWinkHeart
FaFaceKiss
FaFaceLaughBeam
FaFaceLaughSquint
FaFaceLaughWink
FaFaceLaugh
FaFaceMehBlank
FaFaceMeh
FaFaceRollingEyes
FaFaceSadCry
FaFaceSadTear
FaFaceSmileBeam
FaFaceSmileWink
FaFaceSmile
FaFaceSurprise
FaFaceTired
FaFan
FaFaucetDrip
FaFaucet
FaFax
FaFeatherPointed
FaFeather
FaFerry
FaFileArrowDown
FaFileArrowUp
FaFileAudio
FaFileCircleCheck
FaFileCircleExclamation
FaFileCircleMinus
FaFileCirclePlus
FaFileCircleQuestion
FaFileCircleXmark
FaFileCode
FaFileContract
FaFileCsv
FaFileExcel
FaFileExport
FaFileImage
FaFileImport
FaFileInvoiceDollar
FaFileInvoice
FaFileLines
FaFileMedical
FaFilePdf
FaFilePen
FaFilePowerpoint
FaFilePrescription
FaFileShield
FaFileSignature
FaFileVideo
FaFileWaveform
FaFileWord
FaFileZipper
FaFile
FaFillDrip
FaFill
FaFilm
FaFilterCircleDollar
FaFilterCircleXmark
FaFilter
FaFingerprint
FaFireBurner
FaFireExtinguisher
FaFireFlameCurved
FaFireFlameSimple
FaFire
FaFishFins
FaFish
FaFlagCheckered
FaFlagUsa
FaFlag
FaFlaskVial
FaFlask
FaFloppyDisk
FaFlorinSign
FaFolderClosed
FaFolderMinus
FaFolderOpen
FaFolderPlus
FaFolderTree
FaFolder
FaFont
FaFootball
FaForwardFast
FaForwardStep
FaForward
FaFrancSign
FaFrog
FaFutbol
FaG
FaGamepad
FaGasPump
FaGaugeHigh
FaGaugeSimpleHigh
FaGaugeSimple
FaGauge
FaGavel
FaGear
FaGears
FaGem
FaGenderless
FaGhost
FaGift
FaGifts
FaGlassWaterDroplet
FaGlassWater
FaGlasses
FaGlobe
FaGolfBallTee
FaGopuram
FaGraduationCap
FaGreaterThanEqual
FaGreaterThan
FaGripLinesVertical
FaGripLines
FaGripVertical
FaGrip
FaGroupArrowsRotate
FaGuaraniSign
FaGuitar
FaGun
FaH
FaHammer
FaHamsa
FaHandBackFist
FaHandDots
FaHandFist
FaHandHoldingDollar
FaHandHoldingDroplet
FaHandHoldingHand
FaHandHoldingHeart
FaHandHoldingMedical
FaHandHolding
FaHandLizard
FaHandMiddleFinger
FaHandPeace
FaHandPointDown
FaHandPointLeft
FaHandPointRight
FaHandPointUp
FaHandPointer
FaHandScissors
FaHandSparkles
FaHandSpock
FaHand
FaHandcuffs
FaHandsAslInterpreting
FaHandsBound
FaHandsBubbles
FaHandsClapping
FaHandsHoldingChild
FaHandsHoldingCircle
FaHandsHolding
FaHandsPraying
FaHands
FaHandshakeAngle
FaHandshakeSimpleSlash
FaHandshakeSimple
FaHandshakeSlash
FaHandshake
FaHanukiah
FaHardDrive
FaHashtag
FaHatCowboySide
FaHatCowboy
FaHatWizard
FaHeadSideCoughSlash
FaHeadSideCough
FaHeadSideMask
FaHeadSideVirus
FaHeading
FaHeadphonesSimple
FaHeadphones
FaHeadset
FaHeartCircleBolt
FaHeartCircleCheck
FaHeartCircleExclamation
FaHeartCircleMinus
FaHeartCirclePlus
FaHeartCircleXmark
FaHeartCrack
FaHeartPulse
FaHeart
FaHelicopterSymbol
FaHelicopter
FaHelmetSafety
FaHelmetUn
FaHighlighter
FaHillAvalanche
FaHillRockslide
FaHippo
FaHockeyPuck
FaHollyBerry
FaHorseHead
FaHorse
FaHospitalUser
FaHospital
FaHotTubPerson
FaHotdog
FaHotel
FaHourglassEnd
FaHourglassHalf
FaHourglassStart
FaHourglass
FaHouseChimneyCrack
FaHouseChimneyMedical
FaHouseChimneyUser
FaHouseChimneyWindow
FaHouseChimney
FaHouseCircleCheck
FaHouseCircleExclamation
FaHouseCircleXmark
FaHouseCrack
FaHouseFire
FaHouseFlag
FaHouseFloodWaterCircleArrowRight
FaHouseFloodWater
FaHouseLaptop
FaHouseLock
FaHouseMedicalCircleCheck
FaHouseMedicalCircleExclamation
FaHouseMedicalCircleXmark
FaHouseMedicalFlag
FaHouseMedical
FaHouseSignal
FaHouseTsunami
FaHouseUser
FaHouse
FaHryvniaSign
FaHurricane
FaICursor
FaI
FaIceCream
FaIcicles
FaIcons
FaIdBadge
FaIdCardClip
FaIdCard
FaIgloo
FaImagePortrait
FaImage
FaImages
FaInbox
FaIndent
FaIndianRupeeSign
FaIndustry
FaInfinity
FaInfo
FaItalic
FaJ
FaJarWheat
FaJar
FaJedi
FaJetFighterUp
FaJetFighter
FaJoint
FaJugDetergent
FaK
FaKaaba
FaKey
FaKeyboard
FaKhanda
FaKipSign
FaKitMedical
FaKitchenSet
FaKiwiBird
FaL
FaLandMineOn
FaLandmarkDome
FaLandmarkFlag
FaLandmark
FaLanguage
FaLaptopCode
FaLaptopFile
FaLaptopMedical
FaLaptop
FaLariSign
FaLayerGroup
FaLeaf
FaLeftLong
FaLeftRight
FaLemon
FaLessThanEqual
FaLessThan
FaLifeRing
FaLightbulb
FaLinesLeaning
FaLinkSlash
FaLink
FaLiraSign
FaListCheck
FaListOl
FaListUl
FaList
FaLitecoinSign
FaLocationArrow
FaLocationCrosshairs
FaLocationDot
FaLocationPinLock
FaLocationPin
FaLockOpen
FaLock
FaLocust
FaLungsVirus
FaLungs
FaM
FaMagnet
FaMagnifyingGlassArrowRight
FaMagnifyingGlassChart
FaMagnifyingGlassDollar
FaMagnifyingGlassLocation
FaMagnifyingGlassMinus
FaMagnifyingGlassPlus
FaMagnifyingGlass
FaManatSign
FaMapLocationDot
FaMapLocation
FaMapPin
FaMap
FaMarker
FaMarsAndVenusBurst
FaMarsAndVenus
FaMarsDouble
FaMarsStrokeRight
FaMarsStrokeUp
FaMarsStroke
FaMars
FaMartiniGlassCitrus
FaMartiniGlassEmpty
FaMartiniGlass
FaMaskFace
FaMaskVentilator
FaMask
FaMasksTheater
FaMattressPillow
FaMaximize
FaMedal
FaMemory
FaMenorah
FaMercury
FaMessage
FaMeteor
FaMicrochip
FaMicrophoneLinesSlash
FaMicrophoneLines
FaMicrophoneSlash
FaMicrophone
FaMicroscope
FaMillSign
FaMinimize
FaMinus
FaMitten
FaMobileButton
FaMobileRetro
FaMobileScreenButton
FaMobileScreen
FaMobile
FaMoneyBill1Wave
FaMoneyBill1
FaMoneyBillTransfer
FaMoneyBillTrendUp
FaMoneyBillWave
FaMoneyBillWheat
FaMoneyBill
FaMoneyBills
FaMoneyCheckDollar
FaMoneyCheck
FaMonument
FaMoon
FaMortarPestle
FaMosque
FaMosquitoNet
FaMosquito
FaMotorcycle
FaMound
FaMountainCity
FaMountainSun
FaMountain
FaMugHot
FaMugSaucer
FaMusic
FaN
FaNairaSign
FaNetworkWired
FaNeuter
FaNewspaper
FaNotEqual
FaNotdef
FaNoteSticky
FaNotesMedical
FaO
FaObjectGroup
FaObjectUngroup
FaOilCan
FaOilWell
FaOm
FaOtter
FaOutdent
FaP
FaPager
FaPaintRoller
FaPaintbrush
FaPalette
FaPallet
FaPanorama
FaPaperPlane
FaPaperclip
FaParachuteBox
FaParagraph
FaPassport
FaPaste
FaPause
FaPaw
FaPeace
FaPenClip
FaPenFancy
FaPenNib
FaPenRuler
FaPenToSquare
FaPen
FaPencil
FaPeopleArrows
FaPeopleCarryBox
FaPeopleGroup
FaPeopleLine
FaPeoplePulling
FaPeopleRobbery
FaPeopleRoof
FaPepperHot
FaPercent
FaPersonArrowDownToLine
FaPersonArrowUpFromLine
FaPersonBiking
FaPersonBooth
FaPersonBreastfeeding
FaPersonBurst
FaPersonCane
FaPersonChalkboard
FaPersonCircleCheck
FaPersonCircleExclamation
FaPersonCircleMinus
FaPersonCirclePlus
FaPersonCircleQuestion
FaPersonCircleXmark
FaPersonDigging
FaPersonDotsFromLine
FaPersonDressBurst
FaPersonDress
FaPersonDrowning
FaPersonFallingBurst
FaPersonFalling
FaPersonHalfDress
FaPersonHarassing
FaPersonHiking
FaPersonMilitaryPointing
FaPersonMilitaryRifle
FaPersonMilitaryToPerson
FaPersonPraying
FaPersonPregnant
FaPersonRays
FaPersonRifle
FaPersonRunning
FaPersonShelter
FaPersonSkating
FaPersonSkiingNordic
FaPersonSkiing
FaPersonSnowboarding
FaPersonSwimming
FaPersonThroughWindow
FaPersonWalkingArrowLoopLeft
FaPersonWalkingArrowRight
FaPersonWalkingDashedLineArrowRight
FaPersonWalkingLuggage
FaPersonWalkingWithCane
FaPersonWalking
FaPerson
FaPesetaSign
FaPesoSign
FaPhoneFlip
FaPhoneSlash
FaPhoneVolume
FaPhone
FaPhotoFilm
FaPiggyBank
FaPills
FaPizzaSlice
FaPlaceOfWorship
FaPlaneArrival
FaPlaneCircleCheck
FaPlaneCircleExclamation
FaPlaneCircleXmark
FaPlaneDeparture
FaPlaneLock
FaPlaneSlash
FaPlaneUp
FaPlane
FaPlantWilt
FaPlateWheat
FaPlay
FaPlugCircleBolt
FaPlugCircleCheck
FaPlugCircleExclamation
FaPlugCircleMinus
FaPlugCirclePlus
FaPlugCircleXmark
FaPlug
FaPlusMinus
FaPlus
FaPodcast
FaPooStorm
FaPoo
FaPoop
FaPowerOff
FaPrescriptionBottleMedical
FaPrescriptionBottle
FaPrescription
FaPrint
FaPumpMedical
FaPumpSoap
FaPuzzlePiece
FaQ
FaQrcode
FaQuestion
FaQuoteLeft
FaQuoteRight
FaR
FaRadiation
FaRadio
FaRainbow
FaRankingStar
FaReceipt
FaRecordVinyl
FaRectangleAd
FaRectangleList
FaRectangleXmark
FaRecycle
FaRegistered
FaRepeat
FaReplyAll
FaReply
FaRepublican
FaRestroom
FaRetweet
FaRibbon
FaRightFromBracket
FaRightLeft
FaRightLong
FaRightToBracket
FaRing
FaRoadBarrier
FaRoadBridge
FaRoadCircleCheck
FaRoadCircleExclamation
FaRoadCircleXmark
FaRoadLock
FaRoadSpikes
FaRoad
FaRobot
FaRocket
FaRotateLeft
FaRotateRight
FaRotate
FaRoute
FaRss
FaRubleSign
FaRug
FaRulerCombined
FaRulerHorizontal
FaRulerVertical
FaRuler
FaRupeeSign
FaRupiahSign
FaS
FaSackDollar
FaSackXmark
FaSailboat
FaSatelliteDish
FaSatellite
FaScaleBalanced
FaScaleUnbalancedFlip
FaScaleUnbalanced
FaSchoolCircleCheck
FaSchoolCircleExclamation
FaSchoolCircleXmark
FaSchoolFlag
FaSchoolLock
FaSchool
FaScissors
FaScrewdriverWrench
FaScrewdriver
FaScrollTorah
FaScroll
FaSdCard
FaSection
FaSeedling
FaServer
FaShapes
FaShareFromSquare
FaShareNodes
FaShare
FaSheetPlastic
FaShekelSign
FaShieldCat
FaShieldDog
FaShieldHalved
FaShieldHeart
FaShieldVirus
FaShield
FaShip
FaShirt
FaShoePrints
FaShopLock
FaShopSlash
FaShop
FaShower
FaShrimp
FaShuffle
FaShuttleSpace
FaSignHanging
FaSignal
FaSignature
FaSignsPost
FaSimCard
FaSink
FaSitemap
FaSkullCrossbones
FaSkull
FaSlash
FaSleigh
FaSliders
FaSmog
FaSmoking
FaSnowflake
FaSnowman
FaSnowplow
FaSoap
FaSocks
FaSolarPanel
FaSortDown
FaSortUp
FaSort
FaSpa
FaSpaghettiMonsterFlying
FaSpellCheck
FaSpider
FaSpinner
FaSplotch
FaSpoon
FaSprayCanSparkles
FaSprayCan
FaSquareArrowUpRight
FaSquareCaretDown
FaSquareCaretLeft
FaSquareCaretRight
FaSquareCaretUp
FaSquareCheck
FaSquareEnvelope
FaSquareFull
FaSquareH
FaSquareMinus
FaSquareNfi
FaSquareParking
FaSquarePen
FaSquarePersonConfined
FaSquarePhoneFlip
FaSquarePhone
FaSquarePlus
FaSquarePollHorizontal
FaSquarePollVertical
FaSquareRootVariable
FaSquareRss
FaSquareShareNodes
FaSquareUpRight
FaSquareVirus
FaSquareXmark
FaSquare
FaStaffSnake
FaStairs
FaStamp
FaStapler
FaStarAndCrescent
FaStarHalfStroke
FaStarHalf
FaStarOfDavid
FaStarOfLife
FaStar
FaSterlingSign
FaStethoscope
FaStop
FaStopwatch20
FaStopwatch
FaStoreSlash
FaStore
FaStreetView
FaStrikethrough
FaStroopwafel
FaSubscript
FaSuitcaseMedical
FaSuitcaseRolling
FaSuitcase
FaSunPlantWilt
FaSun
FaSuperscript
FaSwatchbook
FaSynagogue
FaSyringe
FaT
FaTableCellsLarge
FaTableCells
FaTableColumns
FaTableList
FaTableTennisPaddleBall
FaTable
FaTabletButton
FaTabletScreenButton
FaTablet
FaTablets
FaTachographDigital
FaTag
FaTags
FaTape
FaTarpDroplet
FaTarp
FaTaxi
FaTeethOpen
FaTeeth
FaTemperatureArrowDown
FaTemperatureArrowUp
FaTemperatureEmpty
FaTemperatureFull
FaTemperatureHalf
FaTemperatureHigh
FaTemperatureLow
FaTemperatureQuarter
FaTemperatureThreeQuarters
FaTengeSign
FaTentArrowDownToLine
FaTentArrowLeftRight
FaTentArrowTurnLeft
FaTentArrowsDown
FaTent
FaTents
FaTerminal
FaTextHeight
FaTextSlash
FaTextWidth
FaThermometer
FaThumbsDown
FaThumbsUp
FaThumbtack
FaTicketSimple
FaTicket
FaTimeline
FaToggleOff
FaToggleOn
FaToiletPaperSlash
FaToiletPaper
FaToiletPortable
FaToilet
FaToiletsPortable
FaToolbox
FaTooth
FaToriiGate
FaTornado
FaTowerBroadcast
FaTowerCell
FaTowerObservation
FaTractor
FaTrademark
FaTrafficLight
FaTrailer
FaTrainSubway
FaTrainTram
FaTrain
FaTransgender
FaTrashArrowUp
FaTrashCanArrowUp
FaTrashCan
FaTrash
FaTreeCity
FaTree
FaTriangleExclamation
FaTrophy
FaTrowelBricks
FaTrowel
FaTruckArrowRight
FaTruckDroplet
FaTruckFast
FaTruckFieldUn
FaTruckField
FaTruckFront
FaTruckMedical
FaTruckMonster
FaTruckMoving
FaTruckPickup
FaTruckPlane
FaTruckRampBox
FaTruck
FaTty
FaTurkishLiraSign
FaTurnDown
FaTurnUp
FaTv
FaU
FaUmbrellaBeach
FaUmbrella
FaUnderline
FaUniversalAccess
FaUnlockKeyhole
FaUnlock
FaUpDownLeftRight
FaUpDown
FaUpLong
FaUpRightAndDownLeftFromCenter
FaUpRightFromSquare
FaUpload
FaUserAstronaut
FaUserCheck
FaUserClock
FaUserDoctor
FaUserGear
FaUserGraduate
FaUserGroup
FaUserInjured
FaUserLargeSlash
FaUserLarge
FaUserLock
FaUserMinus
FaUserNinja
FaUserNurse
FaUserPen
FaUserPlus
FaUserSecret
FaUserShield
FaUserSlash
FaUserTag
FaUserTie
FaUserXmark
FaUser
FaUsersBetweenLines
FaUsersGear
FaUsersLine
FaUsersRays
FaUsersRectangle
FaUsersSlash
FaUsersViewfinder
FaUsers
FaUtensils
FaV
FaVanShuttle
FaVault
FaVectorSquare
FaVenusDouble
FaVenusMars
FaVenus
FaVestPatches
FaVest
FaVialCircleCheck
FaVialVirus
FaVial
FaVials
FaVideoSlash
FaVideo
FaVihara
FaVirusCovidSlash
FaVirusCovid
FaVirusSlash
FaVirus
FaViruses
FaVoicemail
FaVolcano
FaVolleyball
FaVolumeHigh
FaVolumeLow
FaVolumeOff
FaVolumeXmark
FaVrCardboard
FaW
FaWalkieTalkie
FaWallet
FaWandMagicSparkles
FaWandMagic
FaWandSparkles
FaWarehouse
FaWaterLadder
FaWater
FaWaveSquare
FaWeightHanging
FaWeightScale
FaWheatAwnCircleExclamation
FaWheatAwn
FaWheelchairMove
FaWheelchair
FaWhiskeyGlass
FaWifi
FaWind
FaWindowMaximize
FaWindowMinimize
FaWindowRestore
FaWineBottle
FaWineGlassEmpty
FaWineGlass
FaWonSign
FaWorm
FaWrench
FaXRay
FaX
FaXmark
FaXmarksLines
FaY
FaYenSign
FaYinYang
FaZ
FaRegAddressBook
FaRegAddressCard
FaRegBellSlash
FaRegBell
FaRegBookmark
FaRegBuilding
FaRegCalendarCheck
FaRegCalendarDays
FaRegCalendarMinus
FaRegCalendarPlus
FaRegCalendarXmark
FaRegCalendar
FaRegChartBar
FaRegChessBishop
FaRegChessKing
FaRegChessKnight
FaRegChessPawn
FaRegChessQueen
FaRegChessRook
FaRegCircleCheck
FaRegCircleDot
FaRegCircleDown
FaRegCircleLeft
FaRegCirclePause
FaRegCirclePlay
FaRegCircleQuestion
FaRegCircleRight
FaRegCircleStop
FaRegCircleUp
FaRegCircleUser
FaRegCircleXmark
FaRegCircle
FaRegClipboard
FaRegClock
FaRegClone
FaRegClosedCaptioning
FaRegCommentDots
FaRegComment
FaRegComments
FaRegCompass
FaRegCopy
FaRegCopyright
FaRegCreditCard
FaRegEnvelopeOpen
FaRegEnvelope
FaRegEyeSlash
FaRegEye
FaRegFaceAngry
FaRegFaceDizzy
FaRegFaceFlushed
FaRegFaceFrownOpen
FaRegFaceFrown
FaRegFaceGrimace
FaRegFaceGrinBeamSweat
FaRegFaceGrinBeam
FaRegFaceGrinHearts
FaRegFaceGrinSquintTears
FaRegFaceGrinSquint
FaRegFaceGrinStars
FaRegFaceGrinTears
FaRegFaceGrinTongueSquint
FaRegFaceGrinTongueWink
FaRegFaceGrinTongue
FaRegFaceGrinWide
FaRegFaceGrinWink
FaRegFaceGrin
FaRegFaceKissBeam
FaRegFaceKissWinkHeart
FaRegFaceKiss
FaRegFaceLaughBeam
FaRegFaceLaughSquint
FaRegFaceLaughWink
FaRegFaceLaugh
FaRegFaceMehBlank
FaRegFaceMeh
FaRegFaceRollingEyes
FaRegFaceSadCry
FaRegFaceSadTear
FaRegFaceSmileBeam
FaRegFaceSmileWink
FaRegFaceSmile
FaRegFaceSurprise
FaRegFaceTired
FaRegFileAudio
FaRegFileCode
FaRegFileExcel
FaRegFileImage
FaRegFileLines
FaRegFilePdf
FaRegFilePowerpoint
FaRegFileVideo
FaRegFileWord
FaRegFileZipper
FaRegFile
FaRegFlag
FaRegFloppyDisk
FaRegFolderClosed
FaRegFolderOpen
FaRegFolder
FaRegFontAwesome
FaRegFutbol
FaRegGem
FaRegHandBackFist
FaRegHandLizard
FaRegHandPeace
FaRegHandPointDown
FaRegHandPointLeft
FaRegHandPointRight
FaRegHandPointUp
FaRegHandPointer
FaRegHandScissors
FaRegHandSpock
FaRegHand
FaRegHandshake
FaRegHardDrive
FaRegHeart
FaRegHospital
FaRegHourglassHalf
FaRegHourglass
FaRegIdBadge
FaRegIdCard
FaRegImage
FaRegImages
FaRegKeyboard
FaRegLemon
FaRegLifeRing
FaRegLightbulb
FaRegMap
FaRegMessage
FaRegMoneyBill1
FaRegMoon
FaRegNewspaper
FaRegNoteSticky
FaRegObjectGroup
FaRegObjectUngroup
FaRegPaperPlane
FaRegPaste
FaRegPenToSquare
FaRegRectangleList
FaRegRectangleXmark
FaRegRegistered
FaRegShareFromSquare
FaRegSnowflake
FaRegSquareCaretDown
FaRegSquareCaretLeft
FaRegSquareCaretRight
FaRegSquareCaretUp
FaRegSquareCheck
FaRegSquareFull
FaRegSquareMinus
FaRegSquarePlus
FaRegSquare
FaRegStarHalfStroke
FaRegStarHalf
FaRegStar
FaRegSun
FaRegThumbsDown
FaRegThumbsUp
FaRegTrashCan
FaRegUser
FaRegWindowMaximize
FaRegWindowMinimize
FaRegWindowRestore
`;

const RequestInput: React.FC<RequestInputProps> = ({
    kworkInputRef,
    onCopyToClipboard,
    onClearAll,
    isCopyDisabled,
    isClearDisabled,
    onInputChange,
    initialValue = "",
    // New props
    onAskAi,
    isAskAiDisabled,
    aiActionLoading,
    onAddSelected,
    isAddSelectedDisabled,
    selectedFetcherFilesCount,
}) => {

    const handleChange: ChangeEventHandler<HTMLTextAreaElement> = (e) => {
        if (onInputChange) {
            onInputChange(e.target.value);
        }
    };

    // Handler for copying instructions
    const handleCopyInstructions = () => {
        navigator.clipboard.writeText(BOT_INSTRUCTIONS)
            .then(() => {
                toast.success("Специи для бота готовы, вставляй!)");
            })
            .catch(err => {
                console.error("Failed to copy instructions: ", err);
                toast.error("Ошибка копирования инструкций");
            });
    };

    return (
        <div className="flex flex-col gap-3"> {/* Changed to flex-col */}
            <div className="relative">
                <p className="text-yellow-400 mb-2 text-xs md:text-sm"> 4. Опиши задачу И/ИЛИ добавь файлы кнопкой <FaPlus className="inline text-base mx-1"/>. Затем <FaRobot className="inline text-base mx-1"/> или <FaClipboard className="inline text-base mx-1"/>. </p>
                <textarea
                    id="kwork-input"
                    ref={kworkInputRef}
                    defaultValue={initialValue} // Use defaultValue for uncontrolled with ref
                    onChange={handleChange} // Notify parent on change
                    className="w-full p-3 pr-14 bg-gray-800 rounded-lg border border-gray-700 focus:border-cyan-500 focus:outline-none focus:ring-1 focus:ring-cyan-500 transition shadow-[0_0_8px_rgba(0,255,157,0.3)] resize-y min-h-[120px] text-sm placeholder-gray-500"
                    placeholder="Опиши здесь вашу задачу... Затем добавь контекст кнопками ИЛИ нажми 'Спросить AI'."
                    disabled={isAskAiDisabled && isCopyDisabled && isClearDisabled} // Disable textarea if all actions are disabled
                />
                {/* Icon Buttons Container */}
                <div className="absolute top-8 right-2 flex flex-col gap-2">
                     {/* Copy Instructions Button */}
                     <motion.button
                        onClick={handleCopyInstructions}
                        className="p-1.5 bg-gradient-to-r from-indigo-500 to-purple-500 rounded-full shadow-[0_0_8px_rgba(129,140,248,0.3)] transition-all hover:shadow-[0_0_12px_rgba(167,139,250,0.5)]"
                        whileHover={{ scale: 1.1 }}
                        whileTap={{ scale: 0.9 }}
                        title="Скопировать инструкции для бота (role prompt)"
                    >
                        <FaFileLines className="text-white text-base" />
                    </motion.button>
                    {/* Copy Button */}
                    <motion.button
                        onClick={onCopyToClipboard}
                        disabled={isCopyDisabled}
                        className={`p-1.5 bg-gradient-to-r from-cyan-600 to-teal-500 rounded-full shadow-[0_0_8px_rgba(6,182,212,0.3)] transition-all ${isCopyDisabled ? 'opacity-40 cursor-not-allowed' : 'hover:shadow-[0_0_12px_rgba(6,182,212,0.5)]'}`}
                        whileHover={{ scale: !isCopyDisabled ? 1.1 : 1 }}
                        whileTap={{ scale: !isCopyDisabled ? 0.9 : 1 }}
                        title="Скопировать запрос в буфер (для ручной вставки в AI)"
                    >
                        <FaClipboard className="text-white text-base" />
                    </motion.button>
                    {/* Clear Button */}
                    <motion.button
                        onClick={onClearAll}
                        disabled={isClearDisabled}
                        className={`p-1.5 bg-gradient-to-r from-red-600 to-orange-500 rounded-full shadow-[0_0_8px_rgba(220,38,38,0.3)] transition-all ${isClearDisabled ? 'opacity-40 cursor-not-allowed' : 'hover:shadow-[0_0_12px_rgba(220,38,38,0.5)]'}`}
                        whileHover={{ scale: !isClearDisabled ? 1.1 : 1 }}
                        whileTap={{ scale: !isClearDisabled ? 0.9 : 1 }}
                        title="Очистить поле ввода и выбор файлов"
                    >
                        <FaBroom className="text-white text-base" />
                    </motion.button>
                </div>
            </div>
            {/* Action Buttons below Textarea */}
            <div className="flex flex-col sm:flex-row gap-3">
                 {/* Add Selected Button */}
                 <motion.button
                      onClick={() => onAddSelected()}
                      disabled={isAddSelectedDisabled}
                      className={`flex items-center justify-center gap-2 flex-grow px-4 py-2 rounded-full font-semibold text-sm text-white ${ // Use rounded-full
                        isAddSelectedDisabled
                          ? 'bg-gray-600 opacity-60 cursor-not-allowed'
                          : 'bg-gradient-to-r from-teal-500 to-cyan-500 hover:from-teal-600 hover:to-cyan-600 shadow-md shadow-cyan-500/30 hover:shadow-lg hover:shadow-teal-500/40'
                      } transition-all`}
                      whileHover={{ scale: isAddSelectedDisabled ? 1 : 1.03 }}
                      whileTap={{ scale: isAddSelectedDisabled ? 1 : 0.97 }}
                      title={`Добавить ${selectedFetcherFilesCount} выбранных файлов в запрос`}
                  >
                      <FaPlus />
                      Добавить файлы ({selectedFetcherFilesCount})
                  </motion.button>

                 {/* Ask AI Button */}
                 <motion.button
                    onClick={onAskAi}
                    disabled={isAskAiDisabled}
                    className={`flex items-center justify-center gap-2 w-full sm:w-auto flex-grow px-4 py-2 rounded-full font-semibold text-sm text-white ${ // Use rounded-full
                        isAskAiDisabled
                        ? 'bg-gray-600 opacity-60 cursor-not-allowed'
                        : 'bg-gradient-to-r from-blue-600 to-indigo-500 hover:from-blue-700 hover:to-indigo-600 shadow-md shadow-blue-500/30 hover:shadow-lg hover:shadow-indigo-500/40'
                    } transition-all`}
                    whileHover={{ scale: isAskAiDisabled ? 1 : 1.03 }}
                    whileTap={{ scale: isAskAiDisabled ? 1 : 0.97 }}
                 >
                    {aiActionLoading ? <FaArrowsRotate className="animate-spin" /> : <FaRobot />}
                    {aiActionLoading ? "Спрашиваю..." : "🤖 Спросить AI"}
                 </motion.button>
            </div>
        </div>
    );
};

export default RequestInput;
