// /app/franchize/server-actions/storage-bikes.ts
// ─────────────────────────────────────────────────────────────────────────────
// «Зимнее хранение» — owner-facing wall + tracking server actions (2026-09-27).
//
// The winter-storage contract itself is generated by the flowType="storage"
// checkout (actions-runtime.ts, consolidated doc branch). These actions give
// every move a home afterwards:
//
//   getStorageWallAction        → the «Хранение» wall: staff sees the whole
//                                 season, a logged-in owner sees HIS bikes,
//                                 guests get the offer view (no PII).
//   createStorageBikeAction     → manual add (owner from the Mini App, or
//                                 staff on behalf of a phone caller). NOT
//                                 for rent — these are client machines.
//   updateStorageBikeStatusAction → staff moves: заявка → на хранении →
//                                 возвращён (+ отмена). Every move is
//                                 validated against STORAGE_STATUS_TRANSITIONS,
//                                 logged into storage_bike_events and pushed
//                                 to Telegram (owner + crew) — «notifications
//                                 for every move».
//   addStorageBikeNoteAction    → a note from staff OR the bike's owner.
//
// Identity ladder (mirrors bike-wall.ts / SA-001 lesson — a client-claimed id
// alone grants NOTHING):
//   1. signed Telegram actor cookie (verifyTelegramActorCookieValue),
//   2. raw initData fallback (HMAC vs bot token; claimed actor must match),
//   3. otherwise the caller is a GUEST: read-only offer, zero bike data.
// Staff = crew owner / global admin / ANY active crew member (same as the
// bikes wall). There is deliberately NO password path here — the analytics
// password unlocks money walls, not owner PII in storage.
// ─────────────────────────────────────────────────────────────────────────────

"use server";

import { z } from "zod";
import { supabaseAdmin } from "@/lib/supabase-server";
import { logger } from "@/lib/logger";
import { telegramDeliver } from "@/lib/telegram-transport";
import { resolveLeadNotifyRecipients } from "@/app/franchize/lib/new-lead-notify";
import { resolveCrewBotUsername, crewBotAppLink, platformBotUsername } from "@/app/franchize/lib/crew-bot";
import { formatStorageMonthsLabel } from "@/app/franchize/lib/storage-season";
import {
  canTransitionStorageStatus,
  STORAGE_STORY_EVENTS_CAP,
  storageDocPublicUrl,
  storageFormatRub,
  storageIsoToRu,
  storageMonthsCount,
  storageSeasonDateToIso as toSeasonIso,
  storageStartParam,
  STORAGE_STATUS_META,
  storageStatsOf,
  storageStatusLabel,
  type StorageBikeEventVM,
  type StorageBikeStatus,
  type StorageBikeVM,
  type StorageWallVM,
} from "@/app/franchize/lib/storage";
import { buildStorageBikeReport } from "@/app/franchize/lib/storage-bike-report";

// ── identity ─────────────────────────────────────────────────────────────────

interface StorageActor {
  actorUserId: string;
  isStaff: boolean;
}

function isGlobalAdminRow(user: { role: string | null; status: string | null; metadata: Record<string, unknown> | null } | null): boolean {
  const meta = user?.metadata as Record<string, unknown> | null;
  return (
    user?.role === "admin" ||
    user?.role === "vprAdmin" ||
    user?.status === "admin" ||
    meta?.role === "admin" ||
    meta?.status === "admin"
  );
}

async function staffForActor(actorUserId: string, crewId: string, ownerId: string): Promise<boolean> {
  const { data: user } = await supabaseAdmin
    .from("users")
    .select("role, status, metadata")
    .eq("user_id", actorUserId)
    .maybeSingle();
  if (ownerId === actorUserId || isGlobalAdminRow(user ?? null)) return true;
  const { data: membership } = await supabaseAdmin
    .from("crew_members")
    .select("user_id")
    .eq("crew_id", crewId)
    .eq("user_id", actorUserId)
    .eq("membership_status", "active")
    .maybeSingle();
  return Boolean(membership);
}

/**
 * Resolve the viewer. Returns null for a guest (the wall renders the offer).
 * Identity comes from the signed actor cookie first, then the HMAC-verified
 * initData fallback — exactly the bike-wall ladder.
 */
async function resolveStorageActor(params: {
  slug: string;
  actorUserId?: string;
  initData?: string;
}): Promise<{ crewId: string; actor: StorageActor | null } | null> {
  const slug = params.slug.trim();
  const { data: crew } = await supabaseAdmin
    .from("crews")
    .select("id, owner_id")
    .eq("slug", slug)
    .maybeSingle();
  if (!crew) return null;

  const evaluate = async (actorUserId: string): Promise<StorageActor | null> => {
    const isStaff = await staffForActor(actorUserId, crew.id, crew.owner_id);
    return { actorUserId, isStaff };
  };

  // 1. Signed actor cookie.
  try {
    const { cookies } = await import("next/headers");
    const { TELEGRAM_ACTOR_COOKIE, verifyTelegramActorCookieValue } = await import("@/lib/telegram-actor-cookie");
    const cookieUserId = verifyTelegramActorCookieValue(
      (await cookies()).get(TELEGRAM_ACTOR_COOKIE)?.value,
    );
    if (cookieUserId) {
      return { crewId: crew.id, actor: await evaluate(cookieUserId) };
    }
  } catch (err) {
    logger.warn("[storage] cookie identity check failed:", err instanceof Error ? err.message : String(err));
  }

  // 2. initData fallback — HMAC-verified, claimed id must match the signature.
  if (params.initData && params.actorUserId) {
    try {
      const { computeTelegramWebAppHash } = await import("@/lib/telegram-webapp-auth");
      const botToken = process.env.TELEGRAM_BOT_TOKEN;
      if (botToken) {
        const validation = await computeTelegramWebAppHash(params.initData, botToken);
        if (validation.isValid) {
          const userJson = new URLSearchParams(params.initData).get("user");
          const tgUserId = userJson ? String((JSON.parse(userJson) as { id?: number | string }).id ?? "") : "";
          if (tgUserId && tgUserId === String(params.actorUserId).trim()) {
            return { crewId: crew.id, actor: await evaluate(tgUserId) };
          }
        }
      }
    } catch (err) {
      logger.warn("[storage] initData identity check failed:", err instanceof Error ? err.message : String(err));
    }
  }

  return { crewId: crew.id, actor: null };
}

// ── mapping ──────────────────────────────────────────────────────────────────

interface StorageBikeRow {
  id: string;
  created_at: string;
  status: string;
  owner_user_id: string | null;
  owner_name: string;
  owner_phone: string;
  make: string;
  model: string;
  reg_number: string;
  vin: string;
  bike_year: number | null;
  color: string;
  mileage_km: number | null;
  accessories: string;
  estimated_value_rub: number | null;
  monthly_price_rub: number | null;
  total_price_rub: number | null;
  storage_address: string;
  notice_address: string;
  season_start: string | null;
  season_end: string | null;
  order_id: string | null;
  doc_path: string | null;
  pep_signed: boolean | null;
  paid_until: string | null;
  source: string | null;
}

interface StorageEventRow {
  id: number;
  bike_id: string;
  type: string;
  status: string | null;
  actor_name: string;
  message: string;
  created_at: string;
}

function mapBike(row: StorageBikeRow, events: StorageEventRow[]): StorageBikeVM {
  const source = (row.source ?? "checkout") as StorageBikeVM["source"];
  return {
    id: row.id,
    createdAt: row.created_at,
    status: ((row.status as StorageBikeStatus) || "requested"),
    ownerName: row.owner_name ?? "",
    ownerPhone: row.owner_phone ?? "",
    bikeTitle: [row.make, row.model].filter(Boolean).join(" ").trim() || "Мотоцикл",
    regNumber: row.reg_number ?? "",
    vin: row.vin ?? "",
    year: row.bike_year ?? null,
    color: row.color ?? "",
    mileageKm: row.mileage_km ?? null,
    accessories: row.accessories ?? "",
    estimatedValueRub: Number(row.estimated_value_rub ?? 0),
    monthlyPriceRub: Number(row.monthly_price_rub ?? 0),
    totalPriceRub: Number(row.total_price_rub ?? 0),
    seasonStart: row.season_start,
    seasonEnd: row.season_end,
    monthsLabel: formatStorageMonthsLabel(row.season_start, row.season_end),
    storageAddress: row.storage_address ?? "",
    noticeAddress: row.notice_address ?? "",
    orderId: row.order_id,
    docPath: row.doc_path,
    pepSigned: Boolean(row.pep_signed),
    paidUntil: row.paid_until ?? null,
    source: (["checkout", "owner_add", "crew_add"].includes(source) ? source : "checkout"),
    events: events.map((e) => ({
      id: e.id,
      type: e.type,
      status: (e.status as StorageBikeStatus | null) ?? null,
      actorName: e.actor_name ?? "",
      message: e.message ?? "",
      createdAt: e.created_at,
    })),
  };
}

/** Wall renders ~top events; the story page fetches its own capped history. */
const WALL_EVENTS_PER_CHUNK = 300;

async function loadEventsFor(bikeIds: string[]): Promise<Map<string, StorageEventRow[]>> {
  const byBike = new Map<string, StorageEventRow[]>();
  if (bikeIds.length === 0) return byBike;
  // Chunk to stay well under any in() limits.
  for (let i = 0; i < bikeIds.length; i += 100) {
    const chunk = bikeIds.slice(i, i + 100);
    const { data, error } = await supabaseAdmin
      .from("storage_bike_events")
      .select("id, bike_id, type, status, actor_name, message, created_at")
      .in("bike_id", chunk)
      .order("created_at", { ascending: false })
      .limit(WALL_EVENTS_PER_CHUNK);
    if (error) {
      logger.warn("[storage] events load failed:", error.message);
      continue;
    }
    for (const row of (data ?? []) as unknown as StorageEventRow[]) {
      const list = byBike.get(row.bike_id) ?? [];
      list.push(row);
      byBike.set(row.bike_id, list);
    }
  }
  return byBike;
}

// ── notifications («every move») ─────────────────────────────────────────────

function escHtml(value: string): string {
  return String(value ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

async function notifyStorageMove(params: {
  slug: string;
  text: string;
  /** Extra recipients beyond the crew (e.g. the bike owner). */
  alsoChatIds?: string[];
  /** Recipients to skip (the actor — he just DID the move). */
  excludeChatIds?: string[];
}): Promise<void> {
  const { slug, text, alsoChatIds = [], excludeChatIds = [] } = params;
  try {
    const recipients = new Set<string>();
    // vip-bike style: owner + admins (members get the wall, not the ping).
    for (const id of await resolveLeadNotifyRecipients(slug, { includeMembers: false })) {
      recipients.add(String(id));
    }
    for (const id of alsoChatIds) {
      if (id && /^\d+$/.test(String(id))) recipients.add(String(id));
    }
    for (const id of excludeChatIds) recipients.delete(String(id));
    if (recipients.size === 0) return;
    let botUsername: string | null = null;
    try {
      botUsername = await resolveCrewBotUsername(slug);
    } catch {
      botUsername = null;
    }
    const deeplink = crewBotAppLink(botUsername, storageStartParam(slug));
    const html = `${text}${deeplink ? `\n\n🧊 <a href="${deeplink}">Открыть «Хранение»</a>` : ""}`;
    for (const chatId of recipients) {
      const res = await telegramDeliver("sendMessage", chatId, {
        text: html,
        parse_mode: "HTML",
        disable_web_page_preview: true,
      });
      if (!res.ok) {
        logger.warn("[storage] notify delivery failed", { chatId: String(chatId), error: res.error });
      }
    }
  } catch (err) {
    // Notifications must never break the tracking action itself.
    logger.warn("[storage] notify failed:", err instanceof Error ? err.message : String(err));
  }
}

async function actorDisplayName(actorUserId: string): Promise<string> {
  if (!actorUserId || actorUserId === "system") return "Система";
  try {
    const { data } = await supabaseAdmin
      .from("users")
      .select("full_name, username")
      .eq("user_id", actorUserId)
      .maybeSingle();
    return (data?.full_name || (data?.username ? `@${data.username}` : "") || "Экипаж").trim();
  } catch {
    return "Экипаж";
  }
}

async function insertStorageEvent(params: {
  bikeId: string;
  type: "created" | "status_changed" | "note" | "doc" | "payment" | "owner_linked";
  status?: string | null;
  actor: string;
  actorName: string;
  message: string;
}): Promise<void> {
  const { error } = await supabaseAdmin.from("storage_bike_events").insert({
    bike_id: params.bikeId,
    type: params.type,
    status: params.status ?? null,
    actor: params.actor,
    actor_name: params.actorName,
    message: params.message,
  });
  if (error) {
    logger.warn("[storage] event insert failed:", error.message);
  }
}

// ── actions ──────────────────────────────────────────────────────────────────

const slugSchema = z.object({
  slug: z.string().trim().min(1).max(64),
  actorUserId: z.string().trim().max(64).optional(),
  initData: z.string().trim().max(8192).optional(),
});

export async function getStorageWallAction(input: unknown): Promise<{ success: boolean; wall?: StorageWallVM; error?: string }> {
  const parsed = slugSchema.safeParse(input);
  if (!parsed.success) return { success: false, error: "Некорректный запрос стены хранения." };
  const { slug, actorUserId, initData } = parsed.data;

  const resolved = await resolveStorageActor({ slug, actorUserId, initData });
  if (!resolved) return { success: false, error: "Экипаж не найден." };

  if (!resolved.actor) {
    // Guest: the offer renders, zero bike data crosses the wire.
    const wall: StorageWallVM = { access: "guest", viewerId: null, bikes: [], stats: storageStatsOf([]) };
    return { success: true, wall };
  }

  const { actorUserId: viewerId, isStaff } = resolved.actor;

  let query = supabaseAdmin
    .from("storage_bikes")
    .select("*")
    .eq("crew_slug", slug)
    .order("created_at", { ascending: false })
    .limit(200);
  if (!isStaff) {
    query = query.eq("owner_user_id", viewerId);
  }
  const { data: rows, error } = await query;
  if (error) {
    // Migration not applied yet (manual step) degrades to an empty wall —
    // never a 500 on the owner's screen.
    logger.warn("[storage] wall load failed:", error.message);
    const wall: StorageWallVM = { access: isStaff ? "staff" : "owner", viewerId, bikes: [], stats: storageStatsOf([]) };
    return { success: true, wall };
  }

  const bikeRows = (rows ?? []) as unknown as StorageBikeRow[];
  const eventsByBike = await loadEventsFor(bikeRows.map((r) => r.id));
  const bikes = bikeRows.map((row) => mapBike(row, eventsByBike.get(row.id) ?? []));
  const wall: StorageWallVM = { access: isStaff ? "staff" : "owner", viewerId, bikes, stats: storageStatsOf(bikes) };
  return { success: true, wall };
}

const createStorageBikeSchema = z.object({
  slug: z.string().trim().min(1).max(64),
  actorUserId: z.string().trim().max(64).optional(),
  initData: z.string().trim().max(8192).optional(),
  input: z.object({
    ownerName: z.string().trim().min(2).max(120),
    ownerPhone: z.string().trim().min(6).max(32),
    ownerTgUserId: z.string().trim().regex(/^\d+$/).max(32).optional(),
    bikeTitle: z.string().trim().min(2).max(120),
    regNumber: z.string().trim().max(40).optional(),
    vin: z.string().trim().max(40).optional(),
    year: z.number().int().min(1900).max(2100).optional(),
    color: z.string().trim().max(60).optional(),
    mileageKm: z.number().int().min(0).max(1_000_000).optional(),
    accessories: z.string().trim().max(600).optional(),
    estimatedValueRub: z.number().finite().positive().max(100_000_000),
    monthlyPriceRub: z.number().finite().min(0).max(10_000_000),
    seasonStart: z.string().trim().min(6).max(32),
    seasonEnd: z.string().trim().min(6).max(32),
    storageAddress: z.string().trim().max(300).optional(),
    noticeAddress: z.string().trim().max(300).optional(),
    pepSigned: z.boolean().optional(),
    notes: z.string().trim().max(1000).optional(),
  }),
});

export async function createStorageBikeAction(input: unknown): Promise<{ success: boolean; bikeId?: string; error?: string }> {
  const parsed = createStorageBikeSchema.safeParse(input);
  if (!parsed.success) return { success: false, error: "Заполните марку байка, стоимость и контактные данные." };
  const { slug, initData } = parsed.data;
  const form = parsed.data.input;

  const resolved = await resolveStorageActor({ slug, actorUserId: parsed.data.actorUserId, initData });
  if (!resolved) return { success: false, error: "Экипаж не найден." };
  if (!resolved.actor) {
    return { success: false, error: "Добавить байк можно из Telegram-мини-аппа — откройте приложение через бота." };
  }
  const { actorUserId, isStaff } = resolved.actor;

  const seasonStart = toSeasonIso(form.seasonStart);
  const seasonEnd = toSeasonIso(form.seasonEnd);
  if (!seasonStart || !seasonEnd || storageMonthsCount(seasonStart, seasonEnd) <= 0) {
    return { success: false, error: "Проверьте сезон: дата окончания должна быть позже даты начала." };
  }

  // «Random owners» add their own machines from the Mini App; staff can add
  // on behalf of a phone caller (owner TG unknown → null, claimable later).
  const ownerUserId = isStaff ? (form.ownerTgUserId ?? null) : actorUserId;

  const months = storageMonthsCount(seasonStart, seasonEnd);
  const totalPrice = Math.round(form.monthlyPriceRub * months);

  // INSERT is guarded: a not-yet-migrated DB must not 500 the owner's screen.
  try {
    const { data: inserted, error } = await supabaseAdmin
      .from("storage_bikes")
      .insert({
        crew_slug: slug,
        owner_user_id: ownerUserId,
        owner_name: form.ownerName,
        owner_phone: form.ownerPhone,
        make: form.bikeTitle,
        model: "",
        reg_number: form.regNumber ?? "",
        vin: form.vin ?? "",
        bike_year: form.year ?? null,
        color: form.color ?? "",
        mileage_km: form.mileageKm ?? null,
        accessories: form.accessories ?? "",
        estimated_value_rub: form.estimatedValueRub,
        monthly_price_rub: form.monthlyPriceRub,
        total_price_rub: totalPrice,
        storage_address: form.storageAddress ?? "",
        notice_address: form.noticeAddress ?? "",
        season_start: seasonStart,
        season_end: seasonEnd,
        status: "requested",
        pep_signed: Boolean(form.pepSigned),
        source: isStaff ? "crew_add" : "owner_add",
        notes: form.notes ?? "",
      })
      .select("id")
      .single();
    if (error) throw new Error(error.message);
    const bikeId = String((inserted as { id: string } | null)?.id ?? "");
    if (!bikeId) throw new Error("insert returned no id");

    const actorName = await actorDisplayName(actorUserId);
    await insertStorageEvent({
      bikeId,
      type: "created",
      status: "requested",
      actor: actorUserId,
      actorName,
      message: isStaff
        ? `Добавлено экипажем (${form.ownerName}, ${form.ownerPhone})`
        : "Владелец добавил байк вручную",
    });

    await notifyStorageMove({
      slug,
      text: [
        `❄️ <b>Новый байк на зимнее хранение</b>`,
        `Байк: ${escHtml(form.bikeTitle)}${form.regNumber ? ` (${escHtml(form.regNumber)})` : ""}`,
        `Владелец: ${escHtml(form.ownerName)}, ${escHtml(form.ownerPhone)}`,
        `Сезон: ${storageIsoToRu(seasonStart)} → ${storageIsoToRu(seasonEnd)} (${formatStorageMonthsLabel(seasonStart, seasonEnd) || `${months} мес`})`,
        `Оценка: ${storageFormatRub(form.estimatedValueRub)} ₽ · ${storageFormatRub(form.monthlyPriceRub)} ₽/мес`,
      ].join("\n"),
      // For owner_add the actor IS the owner — the crew ping is enough.
      alsoChatIds: isStaff ? [] : [actorUserId],
      excludeChatIds: [actorUserId],
    });

    return { success: true, bikeId };
  } catch (err) {
    logger.warn("[storage] manual add failed:", err instanceof Error ? err.message : String(err));
    return { success: false, error: "Не удалось сохранить байк — миграция зимнего хранения ещё не применена? Повторите позже." };
  }
}

const updateStorageBikeStatusSchema = z.object({
  slug: z.string().trim().min(1).max(64),
  actorUserId: z.string().trim().max(64).optional(),
  initData: z.string().trim().max(8192).optional(),
  bikeId: z.string().uuid(),
  status: z.enum(["requested", "in_storage", "returned", "cancelled"]),
  message: z.string().trim().max(500).optional(),
});

export async function updateStorageBikeStatusAction(input: unknown): Promise<{ success: boolean; error?: string }> {
  const parsed = updateStorageBikeStatusSchema.safeParse(input);
  if (!parsed.success) return { success: false, error: "Некорректный перевод статуса." };
  const { slug, bikeId, status, message, initData, actorUserId } = parsed.data;

  const resolved = await resolveStorageActor({ slug, actorUserId, initData });
  if (!resolved) return { success: false, error: "Экипаж не найден." };
  if (!resolved.actor?.isStaff) {
    return { success: false, error: "Статус хранения меняет экипаж — запросите менеджера." };
  }
  const { actorUserId: staffId } = resolved.actor;

  const { data: row, error: loadErr } = await supabaseAdmin
    .from("storage_bikes")
    .select("id, status, make, reg_number, owner_name, owner_user_id")
    .eq("id", bikeId)
    .eq("crew_slug", slug)
    .maybeSingle();
  if (loadErr || !row) return { success: false, error: "Байк не найден." };

  const currentStatus = String((row as { status: string }).status || "requested");
  if (currentStatus === status) return { success: true };
  if (!canTransitionStorageStatus(currentStatus, status)) {
    return { success: false, error: `Переход «${storageStatusLabel(currentStatus)}» → «${storageStatusLabel(status)}» недоступен.` };
  }

  const actorName = await actorDisplayName(staffId);
  try {
    const { error: updateErr } = await supabaseAdmin
      .from("storage_bikes")
      .update({ status })
      .eq("id", bikeId)
      .eq("crew_slug", slug);
    if (updateErr) throw new Error(updateErr.message);

    await insertStorageEvent({
      bikeId,
      type: "status_changed",
      status,
      actor: staffId,
      actorName,
      message: message || `${STORAGE_STATUS_META[currentStatus as StorageBikeStatus]?.label ?? storageStatusLabel(currentStatus)} → ${storageStatusLabel(status)}`,
    });
  } catch (err) {
    logger.warn("[storage] status move failed:", err instanceof Error ? err.message : String(err));
    return { success: false, error: "Не удалось сохранить статус — миграция зимнего хранения ещё не применена?" };
  }

  const bike = row as { make: string; reg_number: string; owner_user_id: string | null; owner_name: string };
  const ownerLine = bike.owner_name ? `\nВладелец: ${escHtml(bike.owner_name)}` : "";
  await notifyStorageMove({
    slug,
    text: [
      `❄️ <b>Хранение: ${escHtml(bike.make || "мотоцикл")}${bike.reg_number ? ` (${escHtml(bike.reg_number)})` : ""}</b>`,
      `Статус: ${storageStatusLabel(currentStatus)} → <b>${storageStatusLabel(status)}</b>`,
      `Изменено: ${escHtml(actorName)}`,
      message ? `Комментарий: ${escHtml(message)}` : "",
      ownerLine,
    ].filter(Boolean).join("\n"),
    // The owner hears about every move (if his TG is known and he is not the actor).
    alsoChatIds: bike.owner_user_id ? [String(bike.owner_user_id)] : [],
    excludeChatIds: [staffId],
  });

  return { success: true };
}

const addStorageBikeNoteSchema = z.object({
  slug: z.string().trim().min(1).max(64),
  actorUserId: z.string().trim().max(64).optional(),
  initData: z.string().trim().max(8192).optional(),
  bikeId: z.string().uuid(),
  message: z.string().trim().min(1).max(500),
});

export async function addStorageBikeNoteAction(input: unknown): Promise<{ success: boolean; error?: string }> {
  const parsed = addStorageBikeNoteSchema.safeParse(input);
  if (!parsed.success) return { success: false, error: "Напишите текст заметки." };
  const { slug, bikeId, message, initData, actorUserId } = parsed.data;

  const resolved = await resolveStorageActor({ slug, actorUserId, initData });
  if (!resolved) return { success: false, error: "Экипаж не найден." };
  if (!resolved.actor) return { success: false, error: "Заметки доступны авторизованным пользователям Telegram." };

  const { actorUserId: senderId, isStaff } = resolved.actor;

  const { data: row, error: loadErr } = await supabaseAdmin
    .from("storage_bikes")
    .select("id, make, reg_number, owner_user_id")
    .eq("id", bikeId)
    .eq("crew_slug", slug)
    .maybeSingle();
  if (loadErr || !row) return { success: false, error: "Байк не найден." };
  const bike = row as { make: string; reg_number: string; owner_user_id: string | null };
  // Staff notes on any bike; an owner may annotate HIS bike only.
  if (!isStaff && (!bike.owner_user_id || String(bike.owner_user_id) !== senderId)) {
    return { success: false, error: "Заметку можно оставить только по своему байку." };
  }

  const actorName = await actorDisplayName(senderId);
  try {
    await insertStorageEvent({
      bikeId,
      type: "note",
      status: null,
      actor: senderId,
      actorName,
      message,
    });
  } catch (err) {
    logger.warn("[storage] note failed:", err instanceof Error ? err.message : String(err));
    return { success: false, error: "Не удалось сохранить заметку — миграция зимнего хранения ещё не применена?" };
  }

  await notifyStorageMove({
    slug,
    text: [
      `❄️ <b>Заметка по хранению: ${escHtml(bike.make || "мотоцикл")}${bike.reg_number ? ` (${escHtml(bike.reg_number)})` : ""}</b>`,
      `${escHtml(actorName)}: ${escHtml(message)}`,
    ].join("\n"),
    // Owner note → crew hears it; staff note → owner hears it.
    alsoChatIds: isStaff ? (bike.owner_user_id ? [String(bike.owner_user_id)] : []) : [senderId],
    excludeChatIds: [senderId],
  });

  return { success: true };
}

/** Doc link for the wall card — staff or the bike's owner only. */
export async function getStorageDocUrlAction(input: unknown): Promise<{ success: boolean; url?: string; error?: string }> {
  const parsed = slugSchema.extend({ bikeId: z.string().uuid() }).safeParse(input);
  if (!parsed.success) return { success: false, error: "Некорректный запрос договора." };
  const { slug, bikeId, initData, actorUserId } = parsed.data;

  const resolved = await resolveStorageActor({ slug, actorUserId, initData });
  if (!resolved?.actor) return { success: false, error: "Доступ к договору — по авторизации Telegram." };

  const { data: row, error } = await supabaseAdmin
    .from("storage_bikes")
    .select("doc_path, owner_user_id")
    .eq("id", bikeId)
    .eq("crew_slug", slug)
    .maybeSingle();
  if (error || !row) return { success: false, error: "Байк не найден." };
  const bike = row as { doc_path: string | null; owner_user_id: string | null };
  const isMine = bike.owner_user_id && String(bike.owner_user_id) === resolved.actor.actorUserId;
  if (!resolved.actor.isStaff && !isMine) return { success: false, error: "Договор доступен владельцу и экипажу." };
  if (!bike.doc_path) return { success: true, url: "" };
  return { success: true, url: storageDocPublicUrl(bike.doc_path) };
}

// ── story page / report / payment / owner-link (transparency parity v2) ────

interface StorageStoryLoad {
  row: StorageBikeRow;
  isStaff: boolean;
  isMine: boolean;
  actorUserId: string;
}

/**
 * Load one bike with the crew_slug scope enforced on EVERY query (a valid
 * uuid from another crew must behave exactly like a missing one). Returns
 * null on ANY gate failure — the caller answers with a data-free error so
 * the story page never echoes row data to an unauthorized viewer.
 */
async function loadStoryBike(params: { slug: string; bikeId: string; actorUserId?: string; initData?: string }): Promise<StorageStoryLoad | null> {
  const resolved = await resolveStorageActor({ slug: params.slug, actorUserId: params.actorUserId, initData: params.initData });
  if (!resolved?.actor) return null;
  const { data: row, error } = await supabaseAdmin
    .from("storage_bikes")
    .select("*")
    .eq("id", params.bikeId)
    .eq("crew_slug", params.slug)
    .maybeSingle();
  if (error || !row) return null;
  const bikeRow = row as unknown as StorageBikeRow;
  const isMine = Boolean(bikeRow.owner_user_id) && String(bikeRow.owner_user_id) === resolved.actor.actorUserId;
  if (!resolved.actor.isStaff && !isMine) return null;
  return { row: bikeRow, isStaff: resolved.actor.isStaff, isMine, actorUserId: resolved.actor.actorUserId };
}

async function loadStoryEvents(bikeId: string): Promise<StorageEventRow[]> {
  const { data, error } = await supabaseAdmin
    .from("storage_bike_events")
    .select("id, bike_id, type, status, actor_name, message, created_at")
    .eq("bike_id", bikeId)
    .order("created_at", { ascending: false })
    .limit(STORAGE_STORY_EVENTS_CAP);
  if (error) {
    logger.warn("[storage] story events load failed:", error.message);
    return [];
  }
  return (data ?? []) as unknown as StorageEventRow[];
}

/** The shareable per-bike story («Мотопарк story» parity): staff or owner. */
export async function getStorageBikeStoryAction(input: unknown): Promise<{ success: boolean; story?: StorageBikeVM; access?: "staff" | "owner"; error?: string }> {
  const parsed = slugSchema.extend({ bikeId: z.string().uuid() }).safeParse(input);
  if (!parsed.success) return { success: false, error: "Некорректный запрос карточки хранения." };
  const { slug, bikeId, initData, actorUserId } = parsed.data;

  const loaded = await loadStoryBike({ slug, bikeId, actorUserId, initData });
  if (!loaded) return { success: false, error: "Карточка недоступна: войдите через Telegram как владелец или экипаж." };

  const events = await loadStoryEvents(bikeId);
  return {
    success: true,
    access: loaded.isStaff ? "staff" : "owner",
    story: mapBike(loaded.row, events),
  };
}

const ISO_DATE_RE = /^\d{4}-\d{2}-\d{2}$/;

/**
 * Staff marks the one-shot season payment (contract п. 3 — оплата
 * единовременно). Default target = season_end; a custom date is clamped
 * within ±31 days of the season so a typo can't mark a bike paid into 2030.
 */
export async function markStorageBikePaidAction(input: unknown): Promise<{ success: boolean; error?: string }> {
  const parsed = slugSchema
    .extend({
      bikeId: z.string().uuid(),
      paidUntil: z.string().trim().regex(ISO_DATE_RE, "Дата в формате ГГГГ-ММ-ДД").optional(),
      note: z.string().trim().max(300).optional(),
    })
    .safeParse(input);
  if (!parsed.success) return { success: false, error: "Некорректная отметка оплаты — дата в формате ГГГГ-ММ-ДД." };
  const { slug, bikeId, initData, actorUserId, note } = parsed.data;

  const loaded = await loadStoryBike({ slug, bikeId, actorUserId, initData });
  if (!loaded) return { success: false, error: "Байк не найден." };
  if (!loaded.isStaff) return { success: false, error: "Оплату отмечает экипаж — запросите менеджера." };

  const row = loaded.row;
  let target = parsed.data.paidUntil || row.season_end || "";
  if (!ISO_DATE_RE.test(target)) {
    return { success: false, error: "Укажите дату оплаты (сезон не задан — нет значения по умолчанию)." };
  }
  // Clamp within ±31 days of the season window when the season is known.
  if (row.season_start || row.season_end) {
    const lo = row.season_start ? Date.parse(row.season_start) - 31 * 86400000 : Number.NEGATIVE_INFINITY;
    const hi = row.season_end ? Date.parse(row.season_end) + 31 * 86400000 : Number.POSITIVE_INFINITY;
    const ts = Date.parse(target);
    if (Number.isNaN(ts) || ts < lo || ts > hi) {
      return {
        success: false,
        error: `Дата оплаты должна быть в пределах сезона (${storageIsoToRu(row.season_start) || "—"} → ${storageIsoToRu(row.season_end) || "—"}, ±31 день).`,
      };
    }
    target = new Date(ts).toISOString().slice(0, 10);
  }

  if (row.paid_until === target) return { success: true }; // already marked — no duplicate event

  const staffId = loaded.actorUserId;
  const actorName = await actorDisplayName(staffId);
  try {
    const { error: updateErr } = await supabaseAdmin
      .from("storage_bikes")
      .update({ paid_until: target })
      .eq("id", bikeId)
      .eq("crew_slug", slug);
    if (updateErr) throw new Error(updateErr.message);

    await insertStorageEvent({
      bikeId,
      type: "payment",
      status: null,
      actor: staffId,
      actorName,
      message: `Оплата отмечена до ${storageIsoToRu(target)}${note ? ` — ${note}` : ""}`,
    });
  } catch (err) {
    logger.warn("[storage] payment mark failed:", err instanceof Error ? err.message : String(err));
    return { success: false, error: "Не удалось сохранить отметку оплаты — миграция v2 (paid_until) ещё не применена?" };
  }

  await notifyStorageMove({
    slug,
    text: [
      `❄️ <b>Оплата хранения: ${escHtml(row.make || "мотоцикл")}${row.reg_number ? ` (${escHtml(row.reg_number)})` : ""}</b>`,
      `Оплачено до: <b>${storageIsoToRu(target)}</b>`,
      `Сезон: ${storageFormatRub(row.total_price_rub ?? 0)} ₽`,
      `Отметил: ${escHtml(actorName)}`,
      note ? `Комментарий: ${escHtml(note)}` : "",
    ].filter(Boolean).join("\n"),
    alsoChatIds: row.owner_user_id ? [String(row.owner_user_id)] : [],
    excludeChatIds: [staffId],
  });

  return { success: true };
}

/**
 * Crew attaches a Telegram owner to a bike (web checkouts arrive with
 * owner_user_id = NULL — without this the guest buyer never gets owner
 * transparency). Empty string detaches. STAFF ONLY.
 */
export async function linkStorageBikeOwnerAction(input: unknown): Promise<{ success: boolean; error?: string }> {
  const parsed = slugSchema
    .extend({
      bikeId: z.string().uuid(),
      ownerTgUserId: z.string().trim().max(32).regex(/^\d*$/, "Telegram id — только цифры"),
    })
    .safeParse(input);
  if (!parsed.success) return { success: false, error: "Telegram id владельца — только цифры." };
  const { slug, bikeId, initData, actorUserId } = parsed.data;

  const loaded = await loadStoryBike({ slug, bikeId, actorUserId, initData });
  if (!loaded) return { success: false, error: "Байк не найден." };
  if (!loaded.isStaff) return { success: false, error: "Привязать владельца может только экипаж." };

  const row = loaded.row;
  const digits = parsed.data.ownerTgUserId; // "" = detach
  if (String(row.owner_user_id ?? "") === digits) return { success: true }; // no change

  const staffId = loaded.actorUserId;
  const actorName = await actorDisplayName(staffId);
  try {
    const { error: updateErr } = await supabaseAdmin
      .from("storage_bikes")
      .update({ owner_user_id: digits || null })
      .eq("id", bikeId)
      .eq("crew_slug", slug);
    if (updateErr) throw new Error(updateErr.message);

    await insertStorageEvent({
      bikeId,
      type: "owner_linked",
      status: null,
      actor: staffId,
      actorName,
      message: digits
        ? `Владелец привязан к Telegram (id ${digits}) — стену и уведомления видит владелец`
        : "Привязка владельца снята — заявка остаётся на стене экипажа",
    });
  } catch (err) {
    logger.warn("[storage] owner link failed:", err instanceof Error ? err.message : String(err));
    return { success: false, error: "Не удалось привязать владельца — повторите позже." };
  }

  await notifyStorageMove({
    slug,
    text: [
      `❄️ <b>Хранение: ${escHtml(row.make || "мотоцикл")}${row.reg_number ? ` (${escHtml(row.reg_number)})` : ""}</b>`,
      digits
        ? `Владелец привязан к Telegram — теперь ему видна стена и приходят уведомления`
        : `Привязка владельца снята`,
      `Изменил: ${escHtml(actorName)}`,
    ].join("\n"),
    alsoChatIds: digits ? [digits] : [],
    excludeChatIds: [staffId],
  });

  return { success: true };
}

/** Per-bike markdown one-pager («Отчёт» pill) — staff or the bike's owner. */
export async function getStorageBikeReportAction(input: unknown): Promise<{ success: boolean; data?: { markdown: string; filename: string }; error?: string }> {
  const parsed = slugSchema.extend({ bikeId: z.string().uuid() }).safeParse(input);
  if (!parsed.success) return { success: false, error: "Некорректный запрос отчёта." };
  const { slug, bikeId, initData, actorUserId } = parsed.data;

  const loaded = await loadStoryBike({ slug, bikeId, actorUserId, initData });
  if (!loaded) return { success: false, error: "Отчёт доступен владельцу байка и экипажу." };

  let botUsername: string | null = null;
  try {
    botUsername = (await resolveCrewBotUsername(slug)) || platformBotUsername();
  } catch {
    botUsername = platformBotUsername();
  }
  const wallUrl = crewBotAppLink(botUsername, storageStartParam(slug)) || undefined;
  const docUrl = loaded.row.doc_path ? storageDocPublicUrl(loaded.row.doc_path) : "";

  const events = await loadStoryEvents(bikeId);
  const { data: crewRow } = await supabaseAdmin
    .from("crews")
    .select("name")
    .eq("slug", slug)
    .maybeSingle();
  const crewName = String((crewRow as { name?: string } | null)?.name ?? slug);

  const report = buildStorageBikeReport({
    bike: mapBike(loaded.row, events),
    crewName,
    botUsername: botUsername || undefined,
    wallUrl,
    docUrl: docUrl || undefined,
  });
  return { success: true, data: report };
}
