"""hub-port — Python reference layer for the traversa hub.

Staged in carTest next to the TypeScript originals it mirrors, so the port
into Jeezzzy/traversa is a copy+adapt, not a rewrite:

- ``telegram.py``  — port of ``lib/telegram-webapp-auth.ts`` +
  ``lib/telegram-launch-params.ts`` (official HMAC path, freshness window,
  launch-params extraction). Verified against a golden vector generated by
  carTest's ``scripts/tg_golden_vector.mjs``.
- ``actor.py``     — port of ``lib/connectors/shared/errors.ts``'s
  ``ConnectorCallContext`` + ``shared/http.ts``'s ``contextHeaders``:
  the ``x-megarepo-actor`` / ``x-megarepo-correlation-id`` contract.
- ``crew.py``      — the «dirty way» crew registry: Supabase stays the source
  of truth (``crews`` / ``crew_members`` / ``users``), the hub reads it over
  PostgREST with the service-role key. 60s TTL cache + stale-on-error.
- ``bot_commands.py`` — transport-agnostic decision logic for driving
  OpenCode agent sessions (``src/agents/runner.py`` on the hub) from the
  existing traversa Telegram bot: command parsing, role gating, request
  shaping, reply formatting.

Design rules inherited from the TS side:
- zero app-specific imports; stdlib only (hmac / json / urllib / dataclasses);
- every external-data failure is typed, never a bare ``Exception``;
- the connector/actor contract is byte-compatible with the TS connectors so
  the audit trail (``connector_calls`` by correlationId) stays uniform.
"""

__version__ = "0.1.0"
