"""Telegram Mini App validation — Python port of carTest's
``lib/telegram-webapp-auth.ts`` + ``lib/telegram-launch-params.ts``.

Contract parity with the TypeScript original (pinned by the golden vector in
``tests/test_telegram.py``, generated by ``scripts/tg_golden_vector.mjs``):

- secret     = HMAC-SHA256(key=b"WebAppData", msg=bot_token)  → binary digest
- data-check = "\\n".join(f"{k}={v}") over ALL initData pairs except ``hash``,
               sorted lexicographically by (key, value) *after* URL-decoding
- hash       = HMAC-SHA256(key=secret, msg=data_check).hexdigest()
- the newer Ed25519 ``signature`` field STAYS inside the signed set for
  bot-token HMAC validation (only ``hash`` is excluded) — same as the TS
  original, whose diagnostics list "exclude both hash and signature" as a
  legacy bug.

Known TS↔Python nuance: JS ``<`` compares UTF-16 code units while Python
str compare uses code points; they differ only for non-BMP characters, which
Telegram fields do not contain in practice (emoji live in name fields and
sort identically for all observed initData payloads).
"""

from __future__ import annotations

import hashlib
import hmac
import json
import time
from dataclasses import dataclass
from typing import Any
from urllib.parse import parse_qsl, urlsplit

# auth_date freshness (replay protection) — mirrors TELEGRAM_INIT_DATA_MAX_AGE_MS.
TELEGRAM_INIT_DATA_MAX_AGE_S = 24 * 60 * 60
DEFAULT_FUTURE_TOLERANCE_S = 300


@dataclass(frozen=True)
class ValidationResult:
    """Mirror of TelegramWebAppValidationResult in the TS original."""

    is_valid: bool
    hash_from_client: str | None
    computed_hash: str | None = None
    data_check_string: str | None = None
    error: str | None = None


@dataclass(frozen=True)
class LaunchParams:
    """Mirror of TelegramLaunchParams in ``lib/telegram-launch-params.ts``."""

    init_data: str | None
    start_param: str | None


def _param_pairs(init_data: str) -> list[tuple[str, str]]:
    # keep_blank_values=True → empty values still participate in signing,
    # exactly like URLSearchParams entries in the TS original.
    return parse_qsl(init_data, keep_blank_values=True)


def build_data_check_string(init_data: str) -> tuple[str, str | None]:
    """Official data-check-string: exclude ``hash``, sort by (key, value)."""
    pairs = _param_pairs(init_data)
    hash_from_client = next((v for k, v in pairs if k == "hash"), None)
    signed = sorted((k, v) for k, v in pairs if k != "hash")
    dcs = "\n".join(f"{k}={v}" for k, v in signed)
    return dcs, hash_from_client


def validate_init_data(init_data: str, bot_token: str) -> ValidationResult:
    """Validate initData against the bot token (official HMAC path)."""
    if not bot_token:
        return ValidationResult(False, None, error="bot_token is empty")

    dcs, hash_from_client = build_data_check_string(init_data)
    if not hash_from_client:
        return ValidationResult(
            False, None, data_check_string=dcs, error="Hash not found in initData."
        )

    secret = hmac.new(b"WebAppData", bot_token.encode("utf-8"), hashlib.sha256).digest()
    computed = hmac.new(secret, dcs.encode("utf-8"), hashlib.sha256).hexdigest()
    is_valid = hmac.compare_digest(computed, hash_from_client.lower())
    return ValidationResult(
        is_valid=is_valid,
        hash_from_client=hash_from_client,
        computed_hash=computed,
        data_check_string=dcs,
        error=None if is_valid else "Hash mismatch.",
    )


def get_auth_date(init_data: str) -> int | None:
    """Telegram's own session timestamp (unix seconds), or None."""
    raw = next((v for k, v in _param_pairs(init_data) if k == "auth_date"), None)
    if raw is None:
        return None
    try:
        n = int(raw)
    except ValueError:
        return None
    return n if n > 0 else None


def is_init_data_fresh(
    init_data: str,
    max_age_s: int = TELEGRAM_INIT_DATA_MAX_AGE_S,
    now_s: float | None = None,
    future_tolerance_s: int = DEFAULT_FUTURE_TOLERANCE_S,
) -> bool:
    """True when auth_date is within the window (mirrors the TS freshness gate).

    Missing auth_date → NOT fresh (defensive default for signature-grade use).
    """
    auth_date = get_auth_date(init_data)
    if auth_date is None:
        return False
    now = now_s if now_s is not None else time.time()
    age = now - auth_date
    return -future_tolerance_s <= age <= max_age_s


def parse_user(init_data: str) -> dict[str, Any] | None:
    """JSON-decode the ``user`` field of initData (None when absent/broken)."""
    raw = next((v for k, v in _param_pairs(init_data) if k == "user"), None)
    if not raw:
        return None
    try:
        parsed = json.loads(raw)
    except json.JSONDecodeError:
        return None
    return parsed if isinstance(parsed, dict) else None


def extract_launch_params(url: str) -> LaunchParams:
    """Port of ``extractTelegramLaunchParams``: read tgWebAppData /
    tgWebAppStartParam from the query string first, then the hash fragment.
    First non-empty occurrence wins, query before fragment."""
    try:
        parts = urlsplit(url)
        param_sets = [parse_qsl(parts.query, keep_blank_values=True)]
        fragment = parts.fragment
        if fragment:
            param_sets.append(parse_qsl(fragment, keep_blank_values=True))
    except ValueError:
        return LaunchParams(None, None)

    init_data: str | None = None
    start_param: str | None = None
    for pairs in param_sets:
        for key, value in pairs:
            if key == "tgWebAppData" and not init_data and value.strip():
                init_data = value
            if key == "tgWebAppStartParam" and not start_param and value.strip():
                start_param = value
    return LaunchParams(init_data, start_param)
