export const subcontexts = { // Export subcontexts list for direct access by name
    "Core Application Logic": [
        "next.config.mjs",
        "package.json",
        "tailwind.config.ts",
        "tsconfig.json",
        "types/database.types",
        "app/layout.tsx",
        "components/layout/",
        "app/globals.css",
        "contexts/AppContext.tsx",
        "hooks/supabase.ts",
        "lib/auth.ts",
        "lib/logger.ts",
        "lib/debugLogger.ts",
    ],
    "Arbitrage": [
        "app/arbitrage-explained",
        "app/arbitrage-live-scanner",
        "app/arbitrage-notdummies",
        "app/arbitrage-test-agent",
        "components/arbitrage",
        "app/elon", //contains "GodMode" features in subdirectories
        "app/elon/testbase",
        "supabase/migrations/market_data_1.sql",
        "hooks/useTradeSimulator.ts",
    ],
    "Webhooks and Telegram Bot": [
        "app/api/telegramWebhook/route.ts",
        "app/webhook-handlers",
        "app/actions.ts",
        "telegram.d.ts",
        "hooks/supabase.ts",
    ],
    "CyberFitness (Gamification)": [
        "app/cyberfitness",
        "hooks/cyberFitnessSupabase.ts",
    ],
    "Аренда Кибер-Тачек": [
  "app/rent-car/page.tsx",
  "app/rent/[id]/page.tsx",
  "app/cartest/page.tsx",
  "app/cyber-garage/page.tsx",
  "app/invoices/page.tsx",
  "app/shadow-fleet-admin/page.tsx",
  "app/supercar-test/page.tsx",
  "app/api/search.ts",
  "app/api/telegramWebhook.ts",
  "app/webhook-handlers/car-rental.ts",
  "app/webhook-handlers/proxy.ts",
  "app/webhook-handlers/commands/start.ts",
  "app/webhook-handlers/commands/content/start_survey_questions_sportbike.ts",
  "app/webhook-handlers/commands/content/subcontexts.ts",
  "app/webhook-handlers/ctx.ts",
  "app/webhook-handlers/types.ts",
  "app/webhook-handlers/actions/sendComplexMessage.ts",
  "app/webhook-handlers/command-handler.ts",
  "components/AddCarForm.tsx",
  "components/AnswerOption.tsx",
  "components/CarImage.tsx",
  "components/CarSubmission.tsx",
  "components/RentCarInterface.tsx",
  "components/ResultDisplay.tsx",
  "components/SemanticSearch.tsx",
  "components/ShadowFleetAdmin.tsx",
  "utils/embeddingGenerator.ts",
  "utils/simplifiedEmbeddingGenerator.ts",
  // UI & Layout
  "app/layout.tsx",
  "app/globals.css",
  "app/style-guide/page.tsx",
  "components/Header.tsx",
  "components/layout/BottomNavigation.tsx",
  "components/layout/ClientLayout.tsx",
 // scheme
"supabase/migrations/20240101000000_init.sql",
],
    "Tutorials/Examples": ["app/tutorials", "app/style-guide/page.tsx"],
    "Vibe Content Renderer": [
        "components/VibeContentRenderer.tsx",
        "lib/iconNameMap.ts",
    ],
    "Lead Generation & CRM": [
        "app/leads",
    ],
};