export const CARPIX_BASE = 'https://inmctohsodgdohamhzag.supabase.co/storage/v1/object/public/carpix'

export const fallbackBikes: ConfiguratorBike[] = [
  { id: 'vipbike-g8', make: 'VipBike', model: 'G8', description: 'Электромотоцикл VipBike G8 с мощным двигателем 3000 Вт и максимальной скоростью до 150 км/ч.', daily_price: 120800, image_url: `${CARPIX_BASE}/vipbike-g8/image_0.jpg`, rent_link: '/rent/vipbike-g8', specs: { power_w: 3000, power_kw: 3, max_speed_kmh: '90-150', subtitle: 'Электромотоцикл VipBike G8', tier: 'standard', gallery: [`${CARPIX_BASE}/vipbike-g8/image_1.jpg`, `${CARPIX_BASE}/vipbike-g8/image_2.jpg`, `${CARPIX_BASE}/vipbike-g8/image_3.jpg`], battery_options: { base_price: 120800, batteries: [{ capacity: '50Ah', type: 'regular', battery_price: 44500, total_price: 165300, range_km: '70-110' }, { capacity: '60Ah', type: 'regular', battery_price: 55000, total_price: 175800, range_km: '80-120' }, { capacity: '80Ah', type: 'regular', battery_price: 59000, total_price: 179800, range_km: '90-150' }] } }, type: 'bike', quantity: 1 },
  { id: 'vipbike-g8-2', make: 'VipBike', model: 'G8-2', description: 'Обновленная версия популярной модели G8. Двигатель 3000 Вт, скорость до 150 км/ч.', daily_price: 124400, image_url: `${CARPIX_BASE}/vipbike-g8-2/image_0.jpg`, rent_link: '/rent/vipbike-g8-2', specs: { power_w: 3000, power_kw: 3, max_speed_kmh: '90-150', subtitle: 'Электромотоцикл VipBike G8-2', tier: 'standard', gallery: [`${CARPIX_BASE}/vipbike-g8-2/image_1.jpg`, `${CARPIX_BASE}/vipbike-g8-2/image_2.jpg`, `${CARPIX_BASE}/vipbike-g8-2/image_3.jpg`], battery_options: { base_price: 124400, batteries: [{ capacity: '50Ah', type: 'regular', battery_price: 44500, total_price: 168900, range_km: '70-110' }, { capacity: '60Ah', type: 'regular', battery_price: 55000, total_price: 179400, range_km: '80-120' }, { capacity: '80Ah', type: 'regular', battery_price: 59000, total_price: 183400, range_km: '90-150' }] } }, type: 'bike', quantity: 1 },
  { id: 'vipbike-dmg', make: 'VipBike', model: 'DMG', description: 'Премиальный электромотоцикл VipBike DMG с двигателем 3000 Вт.', daily_price: 159200, image_url: `${CARPIX_BASE}/vipbike-dmg/image_0.jpg`, rent_link: '/rent/vipbike-dmg', specs: { power_w: 3000, power_kw: 3, max_speed_kmh: '90-150', subtitle: 'Премиальный электромотоцикл VipBike DMG', tier: 'premium', gallery: [`${CARPIX_BASE}/vipbike-dmg/image_1.jpg`, `${CARPIX_BASE}/vipbike-dmg/image_2.jpg`, `${CARPIX_BASE}/vipbike-dmg/image_3.jpg`], battery_options: { base_price: 159200, batteries: [{ capacity: '50Ah', type: 'regular', battery_price: 44500, total_price: 203700, range_km: '70-110' }, { capacity: '60Ah', type: 'regular', battery_price: 55000, total_price: 214200, range_km: '80-120' }, { capacity: '80Ah', type: 'regular', battery_price: 59000, total_price: 218200, range_km: '90-150' }] } }, type: 'bike', quantity: 1 },
  { id: 'vipbike-dk', make: 'VipBike', model: 'DK', description: 'Надежный городской байк с двигателем 3000 Вт.', daily_price: 128000, image_url: `${CARPIX_BASE}/vipbike-dk/image_0.jpg`, rent_link: '/rent/vipbike-dk', specs: { power_w: 3000, power_kw: 3, max_speed_kmh: '90-150', tier: 'mid-range', gallery: [`${CARPIX_BASE}/vipbike-dk/image_1.jpg`, `${CARPIX_BASE}/vipbike-dk/image_2.jpg`, `${CARPIX_BASE}/vipbike-dk/image_3.jpg`], battery_options: { base_price: 128000, batteries: [{ capacity: '50Ah', type: 'regular', battery_price: 44500, total_price: 172500, range_km: '70-110' }, { capacity: '60Ah', type: 'regular', battery_price: 55000, total_price: 183000, range_km: '80-120' }, { capacity: '80Ah', type: 'regular', battery_price: 59000, total_price: 187000, range_km: '90-150' }] } }, type: 'bike', quantity: 1 },
  { id: 'vipbike-r1', make: 'VipBike', model: 'R1', description: 'Стильный городской байк с двигателем 3000 Вт.', daily_price: 124400, image_url: `${CARPIX_BASE}/vipbike-r1/image_0.jpg`, rent_link: '/rent/vipbike-r1', specs: { power_w: 3000, power_kw: 3, max_speed_kmh: '90-150', tier: 'standard', gallery: [`${CARPIX_BASE}/vipbike-r1/image_1.jpg`, `${CARPIX_BASE}/vipbike-r1/image_2.jpg`, `${CARPIX_BASE}/vipbike-r1/image_3.jpg`], battery_options: { base_price: 124400, batteries: [{ capacity: '50Ah', type: 'regular', battery_price: 44500, total_price: 168900, range_km: '70-110' }, { capacity: '60Ah', type: 'regular', battery_price: 55000, total_price: 179400, range_km: '80-120' }, { capacity: '80Ah', type: 'regular', battery_price: 59000, total_price: 183400, range_km: '90-150' }] } }, type: 'bike', quantity: 1 },
  { id: 'vipbike-r2', make: 'VipBike', model: 'R2', description: 'Второе поколение популярной R-серии.', daily_price: 124400, image_url: `${CARPIX_BASE}/vipbike-r2/image_0.jpg`, rent_link: '/rent/vipbike-r2', specs: { power_w: 3000, power_kw: 3, max_speed_kmh: '90-150', tier: 'standard', gallery: [`${CARPIX_BASE}/vipbike-r2/image_1.jpg`, `${CARPIX_BASE}/vipbike-r2/image_2.jpg`, `${CARPIX_BASE}/vipbike-r2/image_3.jpg`], battery_options: { base_price: 124400, batteries: [{ capacity: '50Ah', type: 'regular', battery_price: 44500, total_price: 168900, range_km: '70-110' }, { capacity: '60Ah', type: 'regular', battery_price: 55000, total_price: 179400, range_km: '80-120' }, { capacity: '80Ah', type: 'regular', battery_price: 59000, total_price: 183400, range_km: '90-150' }] } }, type: 'bike', quantity: 1 },
  { id: 'vipbike-r3', make: 'VipBike', model: 'R3', description: 'Доступный городской байк с двигателем 3000 Вт.', daily_price: 114800, image_url: `${CARPIX_BASE}/vipbike-r3/image_0.jpg`, rent_link: '/rent/vipbike-r3', specs: { power_w: 3000, power_kw: 3, max_speed_kmh: '90-150', tier: 'budget', gallery: [`${CARPIX_BASE}/vipbike-r3/image_1.jpg`, `${CARPIX_BASE}/vipbike-r3/image_2.jpg`, `${CARPIX_BASE}/vipbike-r3/image_3.jpg`], battery_options: { base_price: 114800, batteries: [{ capacity: '50Ah', type: 'regular', battery_price: 44500, total_price: 159300, range_km: '70-110' }, { capacity: '60Ah', type: 'regular', battery_price: 55000, total_price: 169800, range_km: '80-120' }, { capacity: '80Ah', type: 'regular', battery_price: 59000, total_price: 173800, range_km: '90-150' }] } }, type: 'bike', quantity: 1 },
  { id: 'vipbike-r6', make: 'VipBike', model: 'R6', description: 'Спортивный электромотоцикл с агрессивным дизайном.', daily_price: 148400, image_url: `${CARPIX_BASE}/vipbike-r6/image_0.jpg`, rent_link: '/rent/vipbike-r6', specs: { power_w: 3000, power_kw: 3, max_speed_kmh: '90-150', tier: 'sport', gallery: [`${CARPIX_BASE}/vipbike-r6/image_1.jpg`, `${CARPIX_BASE}/vipbike-r6/image_2.jpg`, `${CARPIX_BASE}/vipbike-r6/image_3.jpg`], battery_options: { base_price: 148400, batteries: [{ capacity: '50Ah', type: 'regular', battery_price: 44500, total_price: 192900, range_km: '70-110' }, { capacity: '60Ah', type: 'regular', battery_price: 55000, total_price: 203400, range_km: '80-120' }, { capacity: '80Ah', type: 'regular', battery_price: 59000, total_price: 207400, range_km: '90-150' }] } }, type: 'bike', quantity: 1 },
  { id: 'vipbike-rz', make: 'VipBike', model: 'RZ', description: 'Бюджетный электромотоцикл с двигателем 3000 Вт.', daily_price: 112400, image_url: `${CARPIX_BASE}/vipbike-rz/image_0.jpg`, rent_link: '/rent/vipbike-rz', specs: { power_w: 3000, power_kw: 3, max_speed_kmh: '90-150', tier: 'budget', gallery: [`${CARPIX_BASE}/vipbike-rz/image_1.jpg`, `${CARPIX_BASE}/vipbike-rz/image_2.jpg`, `${CARPIX_BASE}/vipbike-rz/image_3.jpg`], battery_options: { base_price: 112400, batteries: [{ capacity: '50Ah', type: 'regular', battery_price: 44500, total_price: 156900, range_km: '70-110' }, { capacity: '60Ah', type: 'regular', battery_price: 55000, total_price: 167400, range_km: '80-120' }, { capacity: '80Ah', type: 'regular', battery_price: 59000, total_price: 171400, range_km: '90-150' }] } }, type: 'bike', quantity: 1 },
  { id: 'vipbike-v6', make: 'VipBike', model: 'V6', description: 'Классический дизайн в современном исполнении.', daily_price: 114800, image_url: `${CARPIX_BASE}/vipbike-v6/image_0.jpg`, rent_link: '/rent/vipbike-v6', specs: { power_w: 3000, power_kw: 3, max_speed_kmh: '90-150', tier: 'budget', gallery: [`${CARPIX_BASE}/vipbike-v6/image_1.jpg`, `${CARPIX_BASE}/vipbike-v6/image_2.jpg`, `${CARPIX_BASE}/vipbike-v6/image_3.jpg`], battery_options: { base_price: 114800, batteries: [{ capacity: '50Ah', type: 'regular', battery_price: 44500, total_price: 159300, range_km: '70-110' }, { capacity: '60Ah', type: 'regular', battery_price: 55000, total_price: 169800, range_km: '80-120' }, { capacity: '80Ah', type: 'regular', battery_price: 59000, total_price: 173800, range_km: '90-150' }] } }, type: 'bike', quantity: 1 },
  { id: 'vipbike-jy', make: 'VipBike', model: 'JY', description: 'Оригинальный дизайн, хорошая комплектация.', daily_price: 128000, image_url: `${CARPIX_BASE}/vipbike-jy/image_0.jpg`, rent_link: '/rent/vipbike-jy', specs: { power_w: 3000, power_kw: 3, max_speed_kmh: '90-150', tier: 'mid-range', gallery: [`${CARPIX_BASE}/vipbike-jy/image_1.jpg`, `${CARPIX_BASE}/vipbike-jy/image_2.jpg`, `${CARPIX_BASE}/vipbike-jy/image_3.jpg`], battery_options: { base_price: 128000, batteries: [{ capacity: '50Ah', type: 'regular', battery_price: 44500, total_price: 172500, range_km: '70-110' }, { capacity: '60Ah', type: 'regular', battery_price: 55000, total_price: 183000, range_km: '80-120' }, { capacity: '80Ah', type: 'regular', battery_price: 59000, total_price: 187000, range_km: '90-150' }] } }, type: 'bike', quantity: 1 },
  { id: 'vipbike-xf', make: 'VipBike', model: 'XF', description: 'Динамичный дизайн, отличные ходовые качества.', daily_price: 120800, image_url: `${CARPIX_BASE}/vipbike-xf/image_0.jpg`, rent_link: '/rent/vipbike-xf', specs: { power_w: 3000, power_kw: 3, max_speed_kmh: '90-150', tier: 'standard', gallery: [`${CARPIX_BASE}/vipbike-xf/image_1.jpg`, `${CARPIX_BASE}/vipbike-xf/image_2.jpg`, `${CARPIX_BASE}/vipbike-xf/image_3.jpg`], battery_options: { base_price: 120800, batteries: [{ capacity: '50Ah', type: 'regular', battery_price: 44500, total_price: 165300, range_km: '70-110' }, { capacity: '60Ah', type: 'regular', battery_price: 55000, total_price: 175800, range_km: '80-120' }, { capacity: '80Ah', type: 'regular', battery_price: 59000, total_price: 179800, range_km: '90-150' }] } }, type: 'bike', quantity: 1 },
  { id: 'vipbike-z1000', make: 'VipBike', model: 'Z1000', description: 'Мощный дизайн в стиле японских стритфайтеров.', daily_price: 128000, image_url: `${CARPIX_BASE}/vipbike-z1000/image_0.jpg`, rent_link: '/rent/vipbike-z1000', specs: { power_w: 3000, power_kw: 3, max_speed_kmh: '90-150', tier: 'mid-range', gallery: [`${CARPIX_BASE}/vipbike-z1000/image_1.jpg`, `${CARPIX_BASE}/vipbike-z1000/image_2.jpg`, `${CARPIX_BASE}/vipbike-z1000/image_3.jpg`], battery_options: { base_price: 128000, batteries: [{ capacity: '50Ah', type: 'regular', battery_price: 44500, total_price: 172500, range_km: '70-110' }, { capacity: '60Ah', type: 'regular', battery_price: 55000, total_price: 183000, range_km: '80-120' }, { capacity: '80Ah', type: 'regular', battery_price: 59000, total_price: 187000, range_km: '90-150' }] } }, type: 'bike', quantity: 1 },
  { id: 'vipbike-dn', make: 'VipBike', model: 'DN', description: 'Агрессивный нейкед-стиль, спортивная посадка.', daily_price: 148400, image_url: `${CARPIX_BASE}/vipbike-dn/image_0.jpg`, rent_link: '/rent/vipbike-dn', specs: { power_w: 3000, power_kw: 3, max_speed_kmh: '90-150', tier: 'sport', gallery: [`${CARPIX_BASE}/vipbike-dn/image_1.jpg`, `${CARPIX_BASE}/vipbike-dn/image_2.jpg`, `${CARPIX_BASE}/vipbike-dn/image_3.jpg`], battery_options: { base_price: 148400, batteries: [{ capacity: '50Ah', type: 'regular', battery_price: 44500, total_price: 192900, range_km: '70-110' }, { capacity: '60Ah', type: 'regular', battery_price: 55000, total_price: 203400, range_km: '80-120' }, { capacity: '80Ah', type: 'regular', battery_price: 59000, total_price: 207400, range_km: '90-150' }] } }, type: 'bike', quantity: 1 },
  { id: 'vipbike-a4', make: 'VipBike', model: 'A4', description: 'Флагманский электромотоцикл с двигателем 10000 Вт.', daily_price: 490000, image_url: `${CARPIX_BASE}/vipbike-a4/image_0.jpg`, rent_link: '/rent/vipbike-a4', specs: { power_w: 10000, power_kw: 10, max_speed_kmh: '150+', tier: 'high-performance', gallery: [`${CARPIX_BASE}/vipbike-a4/image_1.jpg`, `${CARPIX_BASE}/vipbike-a4/image_2.jpg`, `${CARPIX_BASE}/vipbike-a4/image_3.jpg`], battery_options: { base_price: 490000, batteries: [{ capacity: 'Included', type: 'lithium', battery_price: 0, total_price: 490000, range_km: '200+' }] } }, type: 'bike', quantity: 1 },
]

export const fallbackParts: ConfiguratorPart[] = [
  { id: 'vipbike-battery-50ah-regular', make: 'VipBike', model: 'Аккумулятор 50Ah (Regular)', description: 'Стандартная аккумуляторная батарея емкостью 50Ah. Запас хода: 70-110 км.', daily_price: 44500, image_url: `${CARPIX_BASE}/parts/battery_50ah.jpg`, specs: { type: 'Battery', capacity: '50Ah', battery_type: 'regular', range_km: '70-110', category: 'battery' }, type: 'parts' },
  { id: 'vipbike-battery-60ah-regular', make: 'VipBike', model: 'Аккумулятор 60Ah (Regular)', description: 'Стандартная аккумуляторная батарея емкостью 60Ah. Запас хода: 80-120 км.', daily_price: 55000, image_url: `${CARPIX_BASE}/parts/battery_60ah.jpg`, specs: { type: 'Battery', capacity: '60Ah', battery_type: 'regular', range_km: '80-120', category: 'battery' }, type: 'parts' },
  { id: 'vipbike-battery-80ah-regular', make: 'VipBike', model: 'Аккумулятор 80Ah (Regular)', description: 'Стандартная аккумуляторная батарея емкостью 80Ah. Запас хода: 90-150 км.', daily_price: 59000, image_url: `${CARPIX_BASE}/parts/battery_80ah.jpg`, specs: { type: 'Battery', capacity: '80Ah', battery_type: 'regular', range_km: '90-150', category: 'battery' }, type: 'parts' },
  { id: 'vipbike-battery-50ah-lithium', make: 'VipBike', model: 'Литиевая батарея 50Ah', description: 'Литиевая аккумуляторная батарея 50Ah. Легче и долговечнее.', daily_price: 82000, image_url: `${CARPIX_BASE}/parts/battery_li_50ah.jpg`, specs: { type: 'Battery', capacity: '50Ah', battery_type: 'lithium', range_km: '70-110', category: 'battery' }, type: 'parts' },
  { id: 'vipbike-battery-60ah-lithium', make: 'VipBike', model: 'Литиевая батарея 60Ah', description: 'Литиевая аккумуляторная батарея 60Ah. Оптимальный выбор.', daily_price: 90000, image_url: `${CARPIX_BASE}/parts/battery_li_60ah.jpg`, specs: { type: 'Battery', capacity: '60Ah', battery_type: 'lithium', range_km: '80-120', category: 'battery' }, type: 'parts' },
  { id: 'vipbike-battery-80ah-lithium', make: 'VipBike', model: 'Литиевая батарея 80Ah', description: 'Литиевая аккумуляторная батарея 80Ah. Увеличенная дальность.', daily_price: 98000, image_url: `${CARPIX_BASE}/parts/battery_li_80ah.jpg`, specs: { type: 'Battery', capacity: '80Ah', battery_type: 'lithium', range_km: '90-150', category: 'battery' }, type: 'parts' },
  { id: 'vipbike-helmet-e4', make: 'VipBike', model: 'Шлем E4 (Tensun)', description: 'Мотоциклетный шлем E4 от Tensun.', daily_price: 8300, image_url: `${CARPIX_BASE}/parts/helmet_e4.jpg`, specs: { type: 'Helmet', brand: 'Tensun', category: 'safety' }, type: 'parts' },
  { id: 'vipbike-motorcycle-helmet', make: 'VipBike', model: 'Мотошлем', description: 'Качественный мотошлем для безопасной езды.', daily_price: 4200, image_url: `${CARPIX_BASE}/parts/helmet.jpg`, specs: { type: 'Helmet', category: 'safety' }, type: 'parts' },
  { id: 'vipbike-abs-system', make: 'VipBike', model: 'ABS система', description: 'Система ABS для безопасного торможения.', daily_price: 16700, image_url: `${CARPIX_BASE}/parts/abs_system.jpg`, specs: { type: 'Safety', system: 'ABS', category: 'brakes' }, type: 'parts' },
  { id: 'vipbike-cbs-system', make: 'VipBike', model: 'Система CBS', description: 'Combi Brake System для сбалансированного торможения.', daily_price: 4200, image_url: `${CARPIX_BASE}/parts/cbs_system.jpg`, specs: { type: 'Safety', system: 'CBS', category: 'brakes' }, type: 'parts' },
  { id: 'vipbike-brembo-brakes', make: 'VipBike', model: 'Тормоза Brembo', description: 'Премиальные тормоза Brembo.', daily_price: 12400, image_url: `${CARPIX_BASE}/parts/brembo_brakes.jpg`, specs: { type: 'Brakes', brand: 'Brembo', category: 'performance' }, type: 'parts' },
  { id: 'vipbike-tft-display', make: 'VipBike', model: 'TFT дисплей', description: 'Цифровой дисплей с поддержкой мобильного телефона.', daily_price: 8300, image_url: `${CARPIX_BASE}/parts/tft_display.jpg`, specs: { type: 'Display', technology: 'TFT', category: 'electronics' }, type: 'parts' },
  { id: 'vipbike-bluetooth-alarm', make: 'VipBike', model: 'Противоугонная Bluetooth', description: 'Противоугонная система с Bluetooth.', daily_price: 5600, image_url: `${CARPIX_BASE}/parts/bluetooth_alarm.jpg`, specs: { type: 'Security', technology: 'Bluetooth', category: 'electronics' }, type: 'parts' },
  { id: 'vipbike-cnc-footpegs', make: 'VipBike', model: 'CNC подножки', description: 'CNC передние и задние подножки.', daily_price: 9700, image_url: `${CARPIX_BASE}/parts/cnc_footpegs.jpg`, specs: { type: 'Footpegs', material: 'CNC Aluminum', category: 'accessories' }, type: 'parts' },
  { id: 'vipbike-front-shock', make: 'VipBike', model: 'Амортизатор передний', description: 'Передний амортизатор.', daily_price: 38600, image_url: `${CARPIX_BASE}/parts/front_shock.jpg`, specs: { type: 'Suspension', position: 'front', category: 'suspension' }, type: 'parts' },
  { id: 'vipbike-rear-shock', make: 'VipBike', model: 'Амортизатор задний', description: 'Задний амортизатор.', daily_price: 16500, image_url: `${CARPIX_BASE}/parts/rear_shock.jpg`, specs: { type: 'Suspension', position: 'rear', category: 'suspension' }, type: 'parts' },
  { id: 'vipbike-rear-tire', make: 'VipBike', model: 'Задняя шина', description: 'Задняя шина для электромотоциклов VipBike.', daily_price: 4200, image_url: `${CARPIX_BASE}/parts/rear_tire.jpg`, specs: { type: 'Tire', position: 'rear', category: 'wheels' }, type: 'parts' },
]

export const lithiumBatteries: ConfiguratorBatteryOption[] = [
  { capacity: '50Ah', type: 'lithium', battery_price: 82000, total_price: 0, range_km: '70-110' },
  { capacity: '60Ah', type: 'lithium', battery_price: 90000, total_price: 0, range_km: '80-120' },
  { capacity: '80Ah', type: 'lithium', battery_price: 98000, total_price: 0, range_km: '90-150' },
  { capacity: '120Ah', type: 'lithium', battery_price: 106000, total_price: 0, range_km: '120-220' },
  { capacity: '160Ah', type: 'lithium', battery_price: 106000, total_price: 0, range_km: '160-260' },
]

export const TIER_META: Record<string, { label: string; color: string }> = {
  budget: { label: 'Бюджет', color: '#6ee7b7' },
  standard: { label: 'Стандарт', color: '#60a5fa' },
  'mid-range': { label: 'Оптимум', color: '#a78bfa' },
  premium: { label: 'Премиум', color: '#fbbf24' },
  sport: { label: 'Спорт', color: '#f87171' },
  'high-performance': { label: 'Флагман', color: '#fb923c' },
}
