-- Daily Contract Insights Cron Job
-- Schedules the daily-insights API endpoint to be called at 9 PM daily
-- (Changed from 9 AM to 9 PM as per user request)
--
-- The endpoint queries rental_contract_artifacts and sale_contract_artifacts
-- tables (contract documents generated by /doc rent/sale flows)
-- and sends a summary to Telegram.
--
-- Requires: CRON_SECRET environment variable to be set in app.settings

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS pg_cron;
CREATE EXTENSION IF NOT EXISTS pg_net;

-- Store secrets in app.settings (if not exists)
INSERT INTO app.settings (key, value)
VALUES ('cron_secret', '13131313')
ON CONFLICT (key) DO NOTHING;

INSERT INTO app.settings (key, value)
VALUES ('telegram_bot_token', '8037950842:AAFpaavB_M_zQtOFFN3kDmg44-EcApLHw9w')
ON CONFLICT (key) DO NOTHING;

INSERT INTO app.settings (key, value)
VALUES ('admin_chat_id', '413553377')
ON CONFLICT (key) DO NOTHING;

-- Schedule daily job at 9 PM server time (21:00)
-- This will call our API which generates the summary and sends via Telegram
SELECT cron.schedule(
  'daily-insights',
  '0 21 * * *',  -- 9 PM every day
  $$
  SELECT
    net.http_post(
      url := 'https://v0-car-test.vercel.app/api/cron/daily-insights',
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'x-cron-secret', (SELECT value FROM app.settings WHERE key = 'cron_secret' LIMIT 1)
      ),
      body := '{}'::jsonb,
      timeout := 30
    );
  $$
);

-- Verify job was scheduled
SELECT * FROM cron.job WHERE jobname = 'daily-insights';

-- To reschedule with new time (e.g., 8 PM):
-- SELECT cron.unschedule('daily-insights');
-- Then re-run the schedule SELECT above with new time.

-- To run manually (for testing):
-- SELECT net.http_post(
--   'https://v0-car-test.vercel.app/api/cron/daily-insights',
--   jsonb_build_object(
--     'Content-Type', 'application/json',
--     'Authorization', 'Bearer ' || (SELECT value FROM app.settings WHERE key = 'cron_secret' LIMIT 1)
--   ),
--   '{}'::jsonb
-- );
