-- ═══════════════════════════════════════════════════════════════════════════
-- Migration: 20260811000001_create_rental_photos.sql
-- Purpose:   I3 — Rental photos MVP (private bucket + metadata table + RLS + counters)
-- PRD:       docs/RENTAL_PHOTO_UPLOAD_PRD.md v1.2 §5.1, §5.2, §5.3
-- Meta:      docs/META_PRD_ITERATIVE_IMPLEMENTATION_PLAN.md Iteration I3
-- ═══════════════════════════════════════════════════════════════════════════
--
-- WHAT THIS CREATES
-- ─────────────────
-- 1. Private Supabase Storage bucket `rental-photos` (1GB free-tier friendly)
-- 2. Metadata table `public.rental_photos` (the actual files live in Storage;
--    this table is the queryable index with SHA-256, dimensions, uploader, etc.)
-- 3. Convenience columns on `public.rentals` for fast KPI queries
--    (avoid joining rental_photos for every list-view render)
-- 4. RLS policies (SELECT for crew members + renter; INSERT/DELETE service-role only)
-- 5. Postgres function `can_access_rental_photo(path, user_id)` for path-based RLS
--
-- DESIGN NOTES
-- ────────────
-- - Bucket is PRIVATE — all reads go through signed URLs generated by the server
--   action `listRentalPhotos` (15-minute TTL). This avoids the public-bucket leak
--   that the existing `rentals` bucket has (photos accessible by guessing URLs).
-- - Files stored as `<rental_id>/<start|end>/<seq>-<timestamp>-<uploader>.jpg`
--   so per-rental cleanup is a single prefix delete.
-- - SHA-256 dedup: same hash + same rental + same photo_type → no re-upload.
-- - No EXIF GPS in v1 (stripped by sharp during server-side compression).
--   GPS opt-in deferred to I4 polish.
--
-- IDEMPOTENCY
-- ───────────
-- ✅ `IF NOT EXISTS` on bucket insert
-- ✅ `CREATE TABLE IF NOT EXISTS`
-- ✅ `ADD COLUMN IF NOT EXISTS`
-- ✅ `CREATE POLICY IF NOT EXISTS` (PG 15+; for older PG, the DO block guards)
-- ✅ `CREATE OR REPLACE FUNCTION`
-- Safe to re-run.
-- ═══════════════════════════════════════════════════════════════════════════


-- ─── 1. Storage bucket ─────────────────────────────────────────────────────
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'rental-photos',
  'rental-photos',
  false,                                -- PRIVATE — signed URLs only
  500 * 1024,                           -- 500 KB hard limit (post-compression)
  ARRAY['image/jpeg', 'image/png', 'image/webp']
)
ON CONFLICT (id) DO NOTHING;

-- Bucket is created via service role in code (ensureBucket pattern from doc-verifier).
-- The INSERT above is a fallback for when the migration runs before the app boots.


-- ─── 2. Metadata table ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.rental_photos (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  rental_id       UUID NOT NULL REFERENCES public.rentals(rental_id) ON DELETE CASCADE,

  -- 'start' = ДО (handoff photo, before rental starts)
  -- 'end'   = ПОСЛЕ (return photo, after rental ends)
  photo_type      TEXT NOT NULL CHECK (photo_type IN ('start', 'end')),

  -- Full path in the bucket: '<rental_id>/<start|end>/<seq>-<timestamp>-<uploader>.jpg'
  storage_path    TEXT NOT NULL,

  -- Post-compression metadata (for audit + storage budgeting)
  file_size_bytes INTEGER NOT NULL,
  sha256_hash     TEXT NOT NULL,         -- tamper detection + dedup
  mime_type       TEXT NOT NULL DEFAULT 'image/jpeg',
  width           INTEGER,               -- pixels, post-compression (nullable for legacy)
  height          INTEGER,               -- pixels, post-compression (nullable for legacy)

  -- Audit: who uploaded + through which surface
  uploaded_by     TEXT NOT NULL REFERENCES users(user_id) ON DELETE SET NULL,
  uploader_role   TEXT NOT NULL CHECK (uploader_role IN ('renter', 'operator', 'admin', 'owner', 'bot')),
  source          TEXT NOT NULL DEFAULT 'webapp' CHECK (source IN ('webapp', 'bot', 'operator_ui', 'drag_drop')),

  -- For soft delete (Phase 4 retention cron hard-deletes after 30 days in trash)
  archived_at     TIMESTAMPTZ,           -- set when moved to rental-photos-archive bucket
  deleted_at      TIMESTAMPTZ,           -- set when soft-deleted (moved to _trash/ prefix)

  -- EXIF + device info (GPS stripped in v1; opt-in deferred to I4)
  metadata        JSONB DEFAULT '{}'::jsonb,

  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for the common query patterns
CREATE INDEX IF NOT EXISTS idx_rental_photos_rental ON public.rental_photos(rental_id);
CREATE INDEX IF NOT EXISTS idx_rental_photos_type   ON public.rental_photos(rental_id, photo_type);
CREATE INDEX IF NOT EXISTS idx_rental_photos_taken  ON public.rental_photos(created_at DESC);

-- Dedup index: one photo per (rental, type, hash) — enforced by unique constraint
CREATE UNIQUE INDEX IF NOT EXISTS uniq_rental_photos_dedup
  ON public.rental_photos(rental_id, photo_type, sha256_hash);


-- ─── 3. Convenience counters on rentals ────────────────────────────────────
-- Avoids a JOIN to rental_photos for every list-view render. Updated by the
-- uploadRentalPhoto + deleteRentalPhoto server actions (manual increment).
ALTER TABLE public.rentals
  ADD COLUMN IF NOT EXISTS start_photo_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS end_photo_count   INTEGER NOT NULL DEFAULT 0;

COMMENT ON COLUMN public.rentals.start_photo_count IS
  'Count of ДО photos (rental_photos where photo_type=start). Updated by uploadRentalPhoto.';
COMMENT ON COLUMN public.rentals.end_photo_count IS
  'Count of ПОСЛЕ photos (rental_photos where photo_type=end). Updated by uploadRentalPhoto.';


-- ─── 4. Path-based access check function (for RLS) ────────────────────────
-- storage.objects doesn't have a rental_id column, so we parse it from the
-- file path. The path schema is: '<rental_id>/<start|end>/<file>.jpg'
-- so the first path segment is the rental_id.
--
-- The function checks if the given user_id is authorized to access that rental:
--   1. Is the user the renter? (rentals.user_id = user_id)
--   2. Is the user a crew member of the bike's crew? (crew_members join)
-- If either is true, return true.
CREATE OR REPLACE FUNCTION public.can_access_rental_photo(
  object_path TEXT,
  user_id TEXT
) RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  path_rental_id TEXT;
  rental_row RECORD;
BEGIN
  -- Path schema: '<rental_id>/<start|end>/<file>.jpg'
  -- Split on '/' and take the first segment.
  path_rental_id := split_part(object_path, '/', 1);

  -- If the path doesn't parse to a UUID, deny.
  IF path_rental_id !~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' THEN
    RETURN FALSE;
  END IF;

  -- Fetch the rental + vehicle crew_id in one shot
  SELECT
    r.user_id,
    r.owner_id,
    c.crew_id
  INTO rental_row
  FROM public.rentals r
  LEFT JOIN public.cars c ON c.id = r.vehicle_id
  WHERE r.rental_id = path_rental_id::uuid;

  IF NOT FOUND THEN
    RETURN FALSE;
  END IF;

  -- Check 1: is the user the renter or owner?
  IF rental_row.user_id = user_id OR rental_row.owner_id = user_id THEN
    RETURN TRUE;
  END IF;

  -- Check 2: is the user a crew member of the bike's crew?
  IF rental_row.crew_id IS NOT NULL THEN
    PERFORM 1
    FROM public.crew_members
    WHERE crew_id = rental_row.crew_id
      AND user_id = user_id
      AND membership_status = 'active'
      AND role IN ('owner', 'admin', 'co_owner', 'member');
    IF FOUND THEN
      RETURN TRUE;
    END IF;
  END IF;

  RETURN FALSE;
END;
$$;

GRANT EXECUTE ON FUNCTION public.can_access_rental_photo(TEXT, TEXT) TO service_role, anon, authenticated;


-- ─── 5. RLS on storage.objects for rental-photos bucket ────────────────────
-- Note: Supabase Storage RLS uses `auth.jwt() ->> 'sub'` for the user_id
-- (NOT auth.uid() — that's for table RLS). However, for the service-role-only
-- INSERT/DELETE pattern we use, the policies are simpler:
--
-- SELECT: allow if can_access_rental_photo returns true (renter or crew member)
-- INSERT: service role only (uploads go through server actions using supabaseAdmin)
-- DELETE: service role only (only the retention cron deletes)
--
-- The SELECT policy uses a SECURITY DEFINER function call so it works for
-- authenticated users (renter using WebApp) without exposing the join logic.
--
-- NOTE: storage RLS policies match on `bucket_id = 'rental-photos'`.

-- Drop existing policies if re-running (DO block guards against PG < 15)
DO $$
BEGIN
  -- SELECT policy
  BEGIN
    DROP POLICY IF EXISTS "rental-photos select for authorized users"
      ON storage.objects;
  EXCEPTION WHEN OTHERS THEN NULL;
  END;

  BEGIN
    CREATE POLICY "rental-photos select for authorized users"
      ON storage.objects FOR SELECT
      USING (
        bucket_id = 'rental-photos'
        AND public.can_access_rental_photo(
          name,
          coalesce(auth.jwt() ->> 'sub', '')
        )
      );
  EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'SELECT policy create skipped: %', SQLERRM;
  END;

  -- INSERT policy — service role only
  BEGIN
    DROP POLICY IF EXISTS "rental-photos insert service role only"
      ON storage.objects;
  EXCEPTION WHEN OTHERS THEN NULL;
  END;

  BEGIN
    CREATE POLICY "rental-photos insert service role only"
      ON storage.objects FOR INSERT
      WITH CHECK (
        bucket_id = 'rental-photos'
        AND auth.role() = 'service_role'
      );
  EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'INSERT policy create skipped: %', SQLERRM;
  END;

  -- DELETE policy — service role only
  BEGIN
    DROP POLICY IF EXISTS "rental-photos delete service role only"
      ON storage.objects;
  EXCEPTION WHEN OTHERS THEN NULL;
  END;

  BEGIN
    CREATE POLICY "rental-photos delete service role only"
      ON storage.objects FOR DELETE
      USING (
        bucket_id = 'rental-photos'
        AND auth.role() = 'service_role'
      );
  EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'DELETE policy create skipped: %', SQLERRM;
  END;
END
$$;


-- ─── 6. RLS on rental_photos table (metadata) ─────────────────────────────
ALTER TABLE public.rental_photos ENABLE ROW LEVEL SECURITY;

-- Drop + recreate policies (idempotent)
DO $$
BEGIN
  -- SELECT: renter or crew member of the rental's bike
  BEGIN
    DROP POLICY IF EXISTS "rental_photos select for authorized users"
      ON public.rental_photos;
  EXCEPTION WHEN OTHERS THEN NULL;
  END;

  BEGIN
    CREATE POLICY "rental_photos select for authorized users"
      ON public.rental_photos FOR SELECT
      USING (
        public.can_access_rental_photo(
          rental_id::text || '/any/any.jpg',  -- synthetic path that parses to rental_id
          coalesce(auth.jwt() ->> 'sub', '')
        )
      );
  EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'rental_photos SELECT policy create skipped: %', SQLERRM;
  END;

  -- INSERT: service role only (server actions using supabaseAdmin)
  BEGIN
    DROP POLICY IF EXISTS "rental_photos insert service role only"
      ON public.rental_photos;
  EXCEPTION WHEN OTHERS THEN NULL;
  END;

  BEGIN
    CREATE POLICY "rental_photos insert service role only"
      ON public.rental_photos FOR INSERT
      WITH CHECK (auth.role() = 'service_role');
  EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'rental_photos INSERT policy create skipped: %', SQLERRM;
  END;

  -- UPDATE: service role only (for soft-delete / archive flags)
  BEGIN
    DROP POLICY IF EXISTS "rental_photos update service role only"
      ON public.rental_photos;
  EXCEPTION WHEN OTHERS THEN NULL;
  END;

  BEGIN
    CREATE POLICY "rental_photos update service role only"
      ON public.rental_photos FOR UPDATE
      USING (auth.role() = 'service_role');
  EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'rental_photos UPDATE policy create skipped: %', SQLERRM;
  END;

  -- DELETE: service role only (hard delete by retention cron)
  BEGIN
    DROP POLICY IF EXISTS "rental_photos delete service role only"
      ON public.rental_photos;
  EXCEPTION WHEN OTHERS THEN NULL;
  END;

  BEGIN
    CREATE POLICY "rental_photos delete service role only"
      ON public.rental_photos FOR DELETE
      USING (auth.role() = 'service_role');
  EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'rental_photos DELETE policy create skipped: %', SQLERRM;
  END;
END
$$;


-- ═══════════════════════════════════════════════════════════════════════════
-- POST-MIGRATION VERIFICATION (run manually in Supabase SQL editor)
-- ═══════════════════════════════════════════════════════════════════════════
--
-- 1. Verify the bucket exists and is private:
--    SELECT id, public, file_size_limit, allowed_mime_types
--    FROM storage.buckets WHERE id = 'rental-photos';
--    -- Expect: public=false, file_size_limit=512000, mime types = image/jpeg,png,webp
--
-- 2. Verify the table + indexes:
--    SELECT count(*) FROM public.rental_photos;  -- 0 (empty)
--    \d public.rental_photos
--
-- 3. Verify the convenience columns on rentals:
--    SELECT start_photo_count, end_photo_count FROM public.rentals LIMIT 1;
--    -- Expect: 0, 0
--
-- 4. Verify the function:
--    SELECT public.can_access_rental_photo('00000000-0000-0000-0000-000000000000/start/test.jpg', 'test-user');
--    -- Expect: false (rental doesn't exist)
--
-- 5. Verify RLS policies:
--    SELECT polname, polcmd FROM pg_policies WHERE tablename = 'rental_photos';
--    -- Expect 4 policies: select, insert, update, delete
-- ═══════════════════════════════════════════════════════════════════════════
