CREATE TABLE notified_opportunities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  -- A unique signature for an opportunity, e.g., "BTC/USDT:binance->bybit"
  opportunity_signature TEXT NOT NULL,
  last_notified_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  -- The core of the debounce logic. We won't notify again until this time has passed.
  cooldown_expires_at TIMESTAMPTZ NOT NULL,
  -- For RLS if needed, and linking to users table
  CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- Create a unique index for fast lookups and to prevent duplicate entries
CREATE UNIQUE INDEX idx_user_opportunity_signature ON notified_opportunities(user_id, opportunity_signature);

-- Grant access to the service_role key used by edge functions
GRANT SELECT, INSERT, UPDATE, DELETE ON notified_opportunities TO service_role;