"""Golden-vector + behaviour tests for hub_port.telegram.

The golden vector below is generated by carTest's scripts/tg_golden_vector.mjs
(implements the EXACT algorithm of lib/telegram-webapp-auth.ts). If the TS
original ever changes, regenerate the vector first — TS stays the source of
truth, this port must follow it.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from hub_port.telegram import (  # noqa: E402
    build_data_check_string,
    extract_launch_params,
    get_auth_date,
    is_init_data_fresh,
    parse_user,
    validate_init_data,
)

BOT_TOKEN = "123456:TEST-GOLDEN-TOKEN"
INIT_DATA = (
    "query_id=AAF9testEAAAAAF9testAg"
    "&user=%7B%22id%22%3A413553377%2C%22first_name%22%3A%22Golden%22%2C%22username%22%3A%22golden_user%22%7D"
    "&auth_date=1770000000"
    "&signature=QtZsQ2fakesignaturevalue"
    "&chat_instance=-7412936502123456789"
    "&chat_type=private"
    "&hash=6483f9941d8c6895610aec739ec4c74618ae5f88bca2e2005218b62a9971deb1"
)
EXPECTED_HASH = "6483f9941d8c6895610aec739ec4c74618ae5f88bca2e2005218b62a9971deb1"
AUTH_DATE = 1770000000


class TestGoldenVector:
    def test_official_path_validates(self):
        result = validate_init_data(INIT_DATA, BOT_TOKEN)
        assert result.is_valid is True, result.error
        assert result.hash_from_client == EXPECTED_HASH
        assert result.computed_hash == EXPECTED_HASH

    def test_data_check_excludes_hash_and_keeps_signature(self):
        dcs, hash_from_client = build_data_check_string(INIT_DATA)
        assert "hash=" not in dcs
        # signature STAYS in the signed set (legacy snippets exclude it — a bug)
        assert "signature=QtZsQ2fakesignaturevalue" in dcs
        assert hash_from_client == EXPECTED_HASH
        # sorted lexicographically by (key, value), \n-joined
        assert dcs.splitlines()[0].startswith("auth_date=")
        assert dcs.splitlines()[1].startswith("chat_instance=")

    def test_wrong_derivation_trap(self):
        # The classic bug: HMAC(bot_token, "WebAppData") instead of
        # HMAC(HMAC("WebAppData", bot_token), dcs). This port must NOT do it.
        import hashlib
        import hmac

        dcs, _ = build_data_check_string(INIT_DATA)
        wrong = hmac.new(
            BOT_TOKEN.encode(), b"WebAppData" + dcs.encode(), hashlib.sha256
        ).hexdigest()
        assert wrong != EXPECTED_HASH

    def test_tampered_payload_rejected(self):
        tampered = INIT_DATA.replace("golden_user", "evil_user")
        result = validate_init_data(tampered, BOT_TOKEN)
        assert result.is_valid is False

    def test_wrong_bot_token_rejected(self):
        result = validate_init_data(INIT_DATA, "123456:OTHER-TOKEN")
        assert result.is_valid is False

    def test_missing_hash_rejected(self):
        no_hash = "&".join(p for p in INIT_DATA.split("&") if not p.startswith("hash="))
        result = validate_init_data(no_hash, BOT_TOKEN)
        assert result.is_valid is False
        assert result.error == "Hash not found in initData."

    def test_empty_bot_token_rejected(self):
        result = validate_init_data(INIT_DATA, "")
        assert result.is_valid is False
        assert result.error == "bot_token is empty"


class TestFreshness:
    def test_fresh_within_window(self):
        now = AUTH_DATE + 3600  # 1h old, window is 24h
        assert is_init_data_fresh(INIT_DATA, now_s=now) is True

    def test_stale_beyond_24h(self):
        now = AUTH_DATE + 25 * 3600
        assert is_init_data_fresh(INIT_DATA, now_s=now) is False

    def test_future_beyond_skew_tolerance(self):
        now = AUTH_DATE - 3600  # more than 5 min in the future
        assert is_init_data_fresh(INIT_DATA, now_s=now) is False

    def test_future_within_skew_tolerance(self):
        now = AUTH_DATE - 60
        assert is_init_data_fresh(INIT_DATA, now_s=now) is True

    def test_missing_auth_date_not_fresh(self):
        no_auth = "&".join(p for p in INIT_DATA.split("&") if not p.startswith("auth_date="))
        assert is_init_data_fresh(no_auth, now_s=AUTH_DATE) is False

    def test_auth_date_parsed(self):
        assert get_auth_date(INIT_DATA) == AUTH_DATE


class TestUserAndLaunchParams:
    def test_parse_user(self):
        user = parse_user(INIT_DATA)
        assert user is not None
        assert user["id"] == 413553377
        assert user["username"] == "golden_user"

    def test_extract_launch_params_from_query(self):
        url = (
            "https://hub.traversa.example/app?tgWebAppData="
            + INIT_DATA.replace("&", "%26")
            + "&tgWebAppStartParam=crew_alpha_confirm_member_1"
        )
        params = extract_launch_params(url)
        assert params.init_data is not None
        assert params.init_data.startswith("query_id=")
        assert params.start_param == "crew_alpha_confirm_member_1"
        # initData survives round-trip validation
        assert validate_init_data(params.init_data, BOT_TOKEN).is_valid is True

    def test_extract_launch_params_from_fragment(self):
        # Real Telegram encodes the initData value inside the fragment.
        from urllib.parse import quote

        url = f"https://hub.traversa.example/app#tgWebAppData={quote(INIT_DATA, safe='')}"
        params = extract_launch_params(url)
        assert params.init_data == INIT_DATA
        assert params.start_param is None

    def test_extract_launch_params_garbage_url(self):
        params = extract_launch_params("not a url at all")
        # urlsplit is lenient — but no tgWebAppData must be found
        assert params.init_data is None
